### ISSUE TITLE
Immutable Environment?

### ISSUE THREAD

**Issue by Arian-D** [mitsuhiko/minijinja#161]
Hey,
Is there a way to not make the environment `mut`able?
For instance instead of
```rust
let mut env = Environment::new();
env.add_template("some-template.html", ...).unwrap();
...
env.add_template("another-template.html", ...).unwrap();
```
is there a function that would let me chain them like this?
```rust
let env = Environment::new()
  .with_template("some-template.html", ...)
  ...
  .with_template("another-template.html", ...);
```

If not, would this be a feature that you'd consider implementing?

**Comment by mitsuhiko** [comment]
What would be the benefit of that? That seems quite specific.

**Comment by Arian-D** [comment]
It's nothing important particularly, but I just felt it would be a bit nicer for error handling and more aligned with functional programming. Currently the functions return a `Result<(), Error>` which are completely fine, but returning `Self` or `Result<Self, Error>` would allow things like `.map` or `.map_err` instead of multiple unwraps or long pattern matches.

**Comment by mitsuhiko** [comment]
But then I need copy on write for everything in the environment which is incredible expensive given how large the structures in it are.

**Comment by mitsuhiko** [comment]
I will close this since I do not believe I will implement this.
