### ISSUE TITLE
Move the instructions in the Instructions struct to be public

### ISSUE THREAD

**Issue by joshuataylor** [mitsuhiko/minijinja#181]
## Description

I'm working on a playground tool for MiniJinja, where I want to show the instructions. Right now, I can get this using debug, but I can't access the instructions for a compiled template, as it's `pub(crate) instructions:`.

Can we use the feature flag  `unstable_machinery` for this? Is that even possible in Rust to do in Rust?

## Reproduction steps

```rust
let compiled = CompiledTemplate::from_name_and_source("playground", &templates_value).unwrap();
for instruction in compiled.instructions {
    ...
}
```

**Comment by joshuataylor** [comment]
Workaround:
```rust
        for i in 0..compiled.instructions.len() {
            let instruction = compiled.instructions.get(i).unwrap_throw();
            ...
        }
```

**Comment by mitsuhiko** [comment]
Why does the given iteration with get/len not work? I would not try to expose the internal vec, even to the unstable machinery.

**Comment by joshuataylor** [comment]
Correct, seems I was mistaken thinking that you couldn't access it otherwise. Sorry for the noise!

**Comment by mitsuhiko** [comment]
BTW in case you're trying to build a playground, maybe the stuff there is useful to you: https://github.com/mitsuhiko/minijinja-playground/

**Comment by joshuataylor** [comment]
Oh that's awesome! Yeah, I wanted to have a play with WASM, and see how MiniJinja worked with it. Looks like we had the same idea!

https://github.com/joshuataylor/minijinja_playground

![image](https://user-images.githubusercontent.com/225131/211696150-ff3cfd49-6976-453f-97a8-bc7bf1ecd9e8.png)
