### ISSUE TITLE
Context has Undefined value if there is the underscore sign in it

### ISSUE THREAD

**Issue by user-name-name** [mitsuhiko/minijinja#196]
## Description

When using the python's binding, the context has "Undefined" value if there is the underscore sign in the context's object.

## Reproduction steps

```python
ctx = {"ctx": {"_fa": {"a": 1}, "fa": {"a": 2}}}

print(minijinja.render_str('string = {{ ctx["fa"]["a"] }}', **ctx))  # works
print(minijinja.render_str('string = {{ ctx["_fa"]["a"] }}', **ctx))  # fails
```

The error is 

```
   1 > string = {{ ctx["_fa"]["a"] }}
     i                ^^^^^^^^^^^^ undefined value
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Referenced variables: {
    ctx: {
        "_fa": Undefined,
        "fa": {
            "a": 2,
        },
    },
}
```

Additional helpful information:

- Version of minijinja: minijinja = "^0.30.1"
- Version of rustc: -
- Operating system and version: MacOs 13.2

## What did you expect

Two examples should work without errors.

**Comment by mitsuhiko** [comment]
That wasn't intentional for dictionaries. Fixed it. It's intentional for objects though so you can hide internals and dunder methods.

**Comment by user-name-name** [comment]
Sorry for lobbying, I asked my collegues to vote but didn't expect they all would do this 😆
