### ISSUE TITLE
Add "other" error variant (or similar)

### ISSUE THREAD

**Issue by SomewhereOutInSpace** [mitsuhiko/minijinja#211]
My use of Minijinja involves hooking a lot of complicated logic into the engine using custom functions and filters. This works *fantastically* well, apart from one small annoyance with error handling: it's not really possible to distinguish between "errors emitted by some Rust code I wrote" and "errors caused by some template code the user wrote."

For the time being, I've settled for tagging my smuggled errors with `UndefinedError`, but that leads to odd/confusing error messages - here's a simple and vaguely contrived example:
```rs
fn raise(message: String) -> MJResult {
    Err(MJError::new(
        MJErrorKind::UndefinedError,
        message
    ))
}
```
```jinja
{{ raise("uh oh") }}
```
```
undefined value: uh oh (in <string>:1)
```
I propose adding a new variant to `Error` - something like `Other` or `External` - to deal with this. 

It doesn't need to carry a payload; that would probably break a lot of stuff and hugely bloat the type's size, ick. Just it existing would be enough for me to appropriately handle things in my own code (do some custom formatting, whatever.)

**Comment by mitsuhiko** [comment]
I would do something like this instead:

```rust
fn raise(message: String) -> MJResult {
    let real_error = MyError::new(message);
    Err(MJError::new(
        MJErrorKind::InvalidOperation,
        "custom error"
    ).with_source(real_error))
}
```

And then in your error handling check if you can downcast the `source` into a `MyError`.

I do think that it makes sense to add more error variants, but I cannot really guarantee that an error variant is never used by the engine itself.

**Comment by SomewhereOutInSpace** [comment]
That makes sense. Thank you for the suggestion (and your time!)
