### ISSUE TITLE
Add an optional chaining operator?

### ISSUE THREAD

**Issue by nokome** [mitsuhiko/minijinja#215]
A couple of times I have found myself wanting to use a JavaScript-like [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in Jinja. e.g

```jinja
{% if object.prop?.subprop >= 1 %}
```

instead of

```jinja
{% if object.prop is not none and object.prop.subprop >= 1 %}
```

**Comment by mitsuhiko** [comment]
I don't think that would do what you want in JavaScript either. `?.` in JavaScript resolves to `undefined` which basically means that you do `undefined >= 1`. This does something else entirely of what your second example shows where the comparison uses short circuiting.

In Jinja I would probably write it like this:

```jinja
{% if object.prop and object.prop.subprop >= 1 %}
```

I'm not _entirely_ opposed to a chaining operator but I would probably also want to land this in Jinja2 then.

**Comment by mitsuhiko** [comment]
I will close this here. I think for this to land in MiniJinja it also needs to land in Jinja.
