### ISSUE TITLE
`{% macro %}` hoisting

### ISSUE THREAD

**Issue by alpharder** [mitsuhiko/minijinja#232]
Hey there,
thanks for your efforts maintaining and sharing this with us.

I'm currently attempting to migrate a huge codebase of Jinja2 compatible (Twig) templates to Minijinja, and macros seem to not be hoisted. 

Consider the following template:

```jinja
{% macro defined_first() %}
  <h1>defined_first</h1>
{% endmacro %}

{% macro defined_second() %}
  {{ defined_first() }}
  <h1>defined_second</h1>
  {{ defined_third() }}
{% endmacro %}

{% macro defined_third() %}
  <h1>defined_third</h1>
{% endmacro %}

{{ defined_second() }}

```

## Actual result – failure
```
Error: invalid operation: value of type undefined is not callable (in template.html:8)
-------------------------------- template.html --------------------------------
   5 | {% macro defined_second() %}
   6 |   {{ defined_first() }}
   7 |   <h1>defined_second</h1>
   8 >   {{ defined_third() }}
     i      ^^^^^^^^^^^^^^^ invalid operation
   9 | {% endmacro %}
  10 | 
  11 | {% macro defined_third() %}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Expected result – rendered template (like @ Jinja2)

```html
  <h1>defined_first</h1>

  <h1>defined_second</h1>
  
  <h1>defined_third</h1>
```

Please let me know if this is intentional and isn't going to be changed. 
Otherwise I'd be happy to attempt submitting a PR (in case this isn't a fundamental architectural limitation).

**Comment by mitsuhiko** [comment]
This is an effect of how the macro closure system is currently implemented and clearly a bug. Macros in Jinja2 are not hoisted either, but they pull in the entire enclosing scope, whereas MiniJinja pulls in only the referenced scoped at the time of the macro declaration.

This should be resolved but I need to investigate what sensible semantics would be here. Happy to accept a patch but I will likely also address this myself.
