### ISSUE TITLE
Support implement `Function` trait manually

### ISSUE THREAD

**Issue by Folyd** [mitsuhiko/minijinja#239]
Currently, the `SealedMarker` prevent the end user implements the `Function` trait. Is there any plan to unseal the `Function` trait?
```rust
pub trait Function<Rv, Args>: Send + Sync + 'static {
    /// Calls a function with the given arguments.
    #[doc(hidden)]
    fn invoke(&self, args: Args, _: SealedMarker) -> Rv;
}
```

**Comment by mitsuhiko** [comment]
There is no plan to unseal this trait because of the complexity of this type. Is there a specific reason why you would it unsealed? You can already create callable objects independently this way anyways:

```rust
#[derive(Debug)]
pub struct MyCallable;

impl fmt::Display for MyCallable {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "<my callable>")
    }
}

impl Object for MyCallable {
    fn call(&self, state: &State, args: &[Value]) -> Result<Value, Error> {
        todo!()
    }
}
```

And then register with `env.add_global("my_callable", Value::from_object(MyCallable))`.

**Comment by Folyd** [comment]
Good to know. Thanks, @mitsuhiko.

**Comment by mitsuhiko** [comment]
I will close this. I assume the proposed solution is good enough.
