### ISSUE TITLE
jinja2.meta.find_undeclared_variables equivalent

### ISSUE THREAD

**Issue by morenol** [mitsuhiko/minijinja#248]
http://code.nabla.net/doc/jinja2/api/jinja2/meta/jinja2.meta.find_undeclared_variables.html

I see that it was implemented but removed in https://github.com/mitsuhiko/minijinja/pull/105

With the custom delimiters feature in place, maybe you could consider PRs adding that feature again?

**Comment by mitsuhiko** [comment]
Very possible to bring it back. I think the bigger question is what you want to use it for so I better understand the motivation.

**Comment by morenol** [comment]
My use case is something like: given something like:

```

   - uses: actions/checkout@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```

Get that I need to add `secrets` to the context so I can pass only what I need to the context. Maybe only `secrets.GITHUB_TOKEN`.

I see that the python library does not have a way to do it (nested undefined variables). Maybe I need to create something like [jsonschema](https://jinja2schema.readthedocs.io/en/latest/) on top of minijinja.


In any case, thanks for bringing back that api again

**Comment by mitsuhiko** [comment]
For what it’s worth it doesn’t do anything for nested constant attribute access.

**Comment by mitsuhiko** [comment]
I'm still not sure about the usefulness of this in the current form. Potentially the nested attribute information would make this at least somewhat more useful. Before releasing I want to reconsider this.

**Comment by fortzi** [comment]
@mitsuhiko In my use case, users have some objects available to use in templates, but they're lazily loaded, as they're expensive to fetch. Knowing the free variables allows to only fetch what's needed for the template.
In fact, this is the only real blocker for me to migrate away from the python implementation of Jinja2 to this much faster implementation.
Is there a chance that this will be exposed in the Python library?
