### ISSUE TITLE
Optimization: allow using the same pre-serialized context for several templates

### ISSUE THREAD

**Issue by llenotre** [mitsuhiko/minijinja#258]
Hello,

Our current usecase of minijinja involves rendering several templates using the same context. However, each time we call the `render` function, `Value::from_serializable` is called: [source](https://github.com/mitsuhiko/minijinja/blob/31474d737e66f31ed96faa0eed934f2fb0a7757d/minijinja/src/template.rs#L89)
This is also the case for `render_to_write`.

Using flamegraph, we found out that in our case, `from_serializable` takes more time to execute than the actual rendering.

What about adding a way to render a template using a pre-serialized context to avoid re-serializing at every time?

Have a great day :)

**Comment by mitsuhiko** [comment]
If you need the same context twice (or parts of it), just use `Value::from_serializable`. This is btw already true if you use `context!`.

```rust
// the value is converted (serialized) into a `Value` once.
let x = minijinja::context!{ ... };
// same with explicit operation:
let val = mininja::Value::from_serializable(...);
```

Afterwards that context can be passed to the render function multiple times and it will not undergo further transformations. That's achieved via a fast-path for value objects. That is documented as part of `render`: https://docs.rs/minijinja/latest/minijinja/struct.Template.html#method.render
