### ISSUE TITLE
MiniJinja 1.0 Alpha Feedback

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/minijinja#283]
MiniJinja 1.0 changes a lot of the APIs, and hopefully to the better. Upgrading however will take a bit of an effort if you use one of the effected APIs.

[Upgrade Notes](https://github.com/mitsuhiko/minijinja/blob/main/CHANGELOG.md#breaking-changes)

If you run into something, in particular if you really dislike a change, please let me know.

**Comment by wrapperup** [comment]
So far the changes are great. I like that State is exposed, that opens up quite a few possibilities.

Only nitpick I have is that it would be nice to keep the `render_block` methods on the template itself, which would do the same thing as `eval_to_state()?.render_block()`. Though I do see that giving them the old API would probably lead them to unnecessarily evaluate the state again if called multiple times, so I think this is perfectly fine.

**Comment by mitsuhiko** [comment]
Yeah I wasn't sure about this myself. I think the chained use is not that bad and it makes it more efficient if you need to render more than one block at the time. In general MiniJinja has a shocking number of methods on all these different structs so I was quite happy getting rid of one :P

**Comment by nokome** [comment]
Thanks for this. Excited to be close to a 1.0.

FWIW, I have an app which makes extensive use of `minijinja` including lots of dynamic objects. I found the upgrade very straightforward, only requiring the change to the new loader API.

**Comment by wolfv** [comment]
We updated `minijinja` in `rattler-build` and didn't have to change anything, so that was pretty painfree. Thanks!
