### ISSUE TITLE
Loader FnMut and lifetime

### ISSUE THREAD

**Issue by fabianfreyer** [mitsuhiko/minijinja#304]
Currently, the loader is an `Fn(&str) -> ... + 'static`. This means that since the loader lives for 'static, there is no way for it to mutate any non-global state. Is there any way to tie the loader to the lifetime of the `Environment` instead of `'static` and make it `FnMut`, allowing a loader to capture a mutable variable that outlives the environment?

As an example use case: I'd like to use [notify] to watch a list of templates (and their transitively included templates). This is done by adding the templates to a mutable [watcher]. I'd like to do something like this:
```rust
let mut watcher = notify::recommended_watcher(/* ... */);
let path_loader = minijinja::path_loader(".")?;
env.set_loader(|name| {
    let path = lookup_path(name)
    watcher.watch(path, false);
    path_loader(name)
});
```

As a side-note, could `path_loader` take a `AsRef<Path>`?

[notify]: https://docs.rs/notify/latest/notify/
[watcher]: https://docs.rs/notify/latest/notify/trait.Watcher.html

**Comment by mitsuhiko** [comment]
The `minijinja-autoreload` crate basically does this outside of the loader. I assume that is not an option for you?

**Comment by fabianfreyer** [comment]
Oh, that `minijinja-autoreload` crate is neat, I'll need to take a look at that! Unfortunately that won't work for me because my templates aren't necessarily files. Re-creating the environment or calling `clear_templates` isn't really an issue though.

Thanks for that snippet, although I have to admit I'm still confused. It's not obvious to me how that closure is `'static`. When I tried to put my mutable state behind an `Arc<Mutex<_>>`, I ran into lifetime issues.

**Comment by mitsuhiko** [comment]
The autoreload crate does not really care about what your loader feeds from. It mainly just provides a pattern of reconstruction (either entire environment or in fast mode just the templates).

> Thanks for that snippet, although I have to admit I'm still confused. It's not obvious to me how that closure is `'static`.

The closure is static because it "owns" the mutex moved in. The `Arc` means that at least as far as the borrow checker is concerned multiple things are an owner of the resource it maintains so the closure does not end up borrowing from the stack.

**Comment by fabianfreyer** [comment]
Thanks!
