### ISSUE TITLE
raw/endraw includes raw/endraw tags in the output

### ISSUE THREAD

**Issue by wez** [mitsuhiko/minijinja#305]
## Description

The tags are included in the output, when I don't believe that they should be.

## Reproduction steps

Modify the hello example to enclose Hello in a raw block:

```diff
diff --git a/examples/hello/src/main.rs b/examples/hello/src/main.rs
index 05119d1..d488681 100644
--- a/examples/hello/src/main.rs
+++ b/examples/hello/src/main.rs
@@ -2,7 +2,7 @@ use minijinja::{context, Environment};

 fn main() {
     let mut env = Environment::new();
-    env.add_template("hello.txt", "Hello {{ name }}!").unwrap();
+    env.add_template("hello.txt", "{% raw %}Hello{% endraw %} {{ name }}!").unwrap();
     let template = env.get_template("hello.txt").unwrap();
     println!("{}", template.render(context!(name => "John")).unwrap());
 }
```

Running it produces this output:

```
{% raw %}Hello{% endraw %} John!
```

Additional helpful information:

- Version of minijinja: 0.30, 0.34 and 1.0 (`main` as of rev 95eb8448d9c4ac706a8c35ad040ee9aac7e1cd3c)
- Version of rustc: `rustc 1.70.0 (90c541806 2023-05-31)`
- Operating system and version: Linux Fedora 38

## What did you expect

I'd expect this output:

```
Hello John!
```

https://jbmoelker.github.io/jinja-compat-tests/tags/raw/ shows some various examples of the raw tag/block syntax in other implementations for the sake of comparison.

**Comment by mitsuhiko** [comment]
Hah yeah. That seems very wrong.

**Comment by wez** [comment]
Thanks!
