### ISSUE TITLE
just a suggestion: comparison between minijinja and tera

### ISSUE THREAD

**Issue by zaxebo1** [mitsuhiko/minijinja#308]
At first thank you for such a wonderful crate

there are few jinja2 like templating solutions in rust, esp.
https://github.com/mitsuhiko/minijinja
https://github.com/Keats/tera

May I suggest to kindly state or publish an article, where you feature wise compare both the above

**Comment by mitsuhiko** [comment]
I think the biggest difference is what you use it for. MiniJinja says were close to Jinja2, to the degree that many templates render in either implementation out of the box. Tera is a template engine inspired by Jinja2 and Django, but does not attempt parity. MiniJinja also at least from my tests performs quite a bit better and has much fewer dependencies (out of the box just `serde`).

MiniJinja also supports dynamic objects and expression evaluation which as far as I know, Tera does not. In general though I'm not terribly familiar with tera so I cannot write such a comparison.
