### ISSUE TITLE
impl ArgType for datetime?

### ISSUE THREAD

**Issue by hongquan** [mitsuhiko/minijinja#313]
I think datetime is a common data type. Please support it.

**Comment by mitsuhiko** [comment]
I would be interested to know which type in particular you expect that implementation for and why you need `ArgType` to support it. You can today already serialize datetimes to values and the datetime formatting filters from `minijinja-contrib` support formatting even without `ArgType` implementing these.

https://docs.rs/minijinja-contrib/latest/minijinja_contrib/filters/fn.datetimeformat.html

**Comment by hongquan** [comment]
I planned to create a custom filter that accept datetime argument (that's why I wanted `ArgType` to support it). But then I figure out that `minijinja` doesn't send "datetime" object to template (https://docs.rs/minijinja/latest/minijinja/value/enum.ValueKind.html). So this desire is impossible.

I tried `minijinja-contrib` but it  only supports DateTime from [time-rs](https://crates.io/crates/time) crate. I don't want to use time-rs in my current object because its behaviour of serialization is weird (it doesn't serialize datetime to RFC 3339 / ISO 8601 string) and the process of formating to RFC 3339 / ISO 8601 is also verbose.

Anyway, thanks. I will try anther way to use MiniJinja with chrono.

**Comment by mitsuhiko** [comment]
@hongquan It should work with chrono. Please open a bug if it does not work with it.
