### ISSUE TITLE
Ability to add entries to a Value

### ISSUE THREAD

**Issue by cking** [mitsuhiko/minijinja#316]
I am in the position that I want to add a new entry to a Value (returned by the `context!()` macro).

I want to create a `render` function that takes the regular context value and adds more fields to it.
Using globals is not possible in this case, because those Values are request specific.
I was thinking about a function, but those can't have states.
Then I read about "abusing" an object variable, but I sadly cant get access to the request session that way, so I want to enhance the regular context values by adding the required values by calling a wrapper function.

Problem being: I cannot get the inner ValueMap, and I prefer not to serialize into serde and back.
Is there any (future) possibility to get a function analog to `get_attr` that allows to set an attribute on the map?

I know that most/all other ValueKinds won't be able to support that function, but it would help me a lot in this case.

I will for now deserialize into serde and then back to minijinja Value.
I hope this suggestion will get some thought anyway.

**Comment by mitsuhiko** [comment]
Regular values are immutable. However your requirement is real and it has come up before. One way to solve this today is to use a custom object that looks up from multiple other values: https://github.com/mitsuhiko/minijinja/blob/main/examples/merge-context/src/main.rs

**Comment by cking** [comment]
That looks more to my use case, thank you!

I would love to have an inbuilt value merging system available, but this helps a ton already!

**Comment by mitsuhiko** [comment]
I definitely want to have something as part of the engine but I haven't found a good solution yet I like.

**Comment by cking** [comment]
this is what i use now:

```rs
use std::{collections::BTreeSet, sync::Arc};

use minijinja::value::{StructObject, Value};

/// A struct that looks up from multiple values.
#[derive(Debug, Default)]
struct MergeContext(Vec<Value>);

impl MergeContext {
    pub fn new(values: Vec<Value>) -> Self {
        Self(values)
    }

    pub fn to_value(self) -> Value {
        Value::from_struct_object(self)
    }
}

impl StructObject for MergeContext {
    fn get_field(&self, field: &str) -> Option<Value> {
        for val in &self.0 {
            match val.get_attr(field) {
                Ok(val) if !val.is_undefined() => return Some(val),
                _ => {}
            }
        }
        None
    }

    fn fields(&self) -> Vec<Arc<str>> {
        let mut rv = BTreeSet::new();
        for val in &self.0 {
            if let Ok(iter) = val.try_iter() {
                for item in iter {
                    if let Some(s) = item.as_str() {
                        if !rv.contains(s) {
                            rv.insert(Arc::from(s.to_string()));
                        }
                    }
                }
            }
        }
        rv.into_iter().collect()
    }
}

macro_rules! merge {
    ($($val:expr),*) => {
        MergeContext::new(vec![$($val),*]).to_value()
    };
}
```

and an example:
```rs
    fn working_with_contexts(val: Value) -> Value {
        merge!(val, context!( more => "data" ))
    }
```

the `merge!` macro makes it easy to use (and understand IMO) and makes the `MergeContext` private.
maybe this can help in your inspiration

**Comment by mitsuhiko** [comment]
I think what could be trivially added is a second syntax to `context!` that merges:

```rust
let ctx = context![...ctx, context! {
    more => "data"
}];
```

**Comment by cking** [comment]
Oh, that would be awesome as well.
I'm liking this one even more. Would remove the need for an extra macro as well
