### ISSUE TITLE
auto impl ArgType trait for a Deserializeable value.

### ISSUE THREAD

**Issue by cathaysia** [mitsuhiko/minijinja#323]
Currently, all filter parameter types need to implement the ArgType trait. This is mainly to implement the from_value function. But while a variable can be convert to Value by serde::serialize, it cannot be vice versa.

Is there a possibility to deserialize the Value back into a variable? Going a step further, is it possible to implement the ArgType trait for all types that implement Deserialize ?

**Comment by cathaysia** [comment]
I use such codes:

```rust
impl<'a> ArgType<'a> for Time {
    type Output = Self;

    fn from_value(value: Option<&'a Value>) -> Result<Self::Output, minijinja::Error> {
        let a = serde_json::to_string(value.unwrap()).unwrap();
        Ok(serde_json::from_str(&a).unwrap())
    }
}
```

**Comment by mitsuhiko** [comment]
I think what this is calling for is probably two things:

- implementing `IntoDeserializer` for `Value`.
- Adding a wrapper type `ViaDeserialize<T>` (name tbd) which uses `IntoDeserializer` and `Deref`s into `T`.

With that one could do something like this:

```rust
fn strftime(time: ViaDeserialize<Time>) -> String {
    time.to_string()
}
```

**Comment by cathaysia** [comment]
Yes, this is also a good solution. But is there an implementation that makes the user imperceptible? For example, if Time implements the Deserialize trait, then it can be used directly:

```rust
fn strftime(time: Time) -> String {
    time.to_string()
}
```

**Comment by mitsuhiko** [comment]
I don't think this can be done without specialization.

**Comment by cathaysia** [comment]
I used the new way instead of the previously implemented procedural macros. it's actually very good. This also fixes the issue of seq not deserializing to vec in the old implementation.

Now suppose there is a type ViaDeserialize<String> Wouldn't it be nice to implement From<String> for ViaDeserialize?

**Comment by mitsuhiko** [comment]
> Wouldn't it be nice to implement From for ViaDeserialize?

It would be a breaking change at the very least and it's likely going to be quite a bit slower for quite a few setups.
