### ISSUE TITLE
Request: support keeping trailing newlines from templates

### ISSUE THREAD

**Issue by mistydemeo** [mitsuhiko/minijinja#333]
Right now, minijinja always strips trailing newlines from template files. The [changelog](https://github.com/mitsuhiko/minijinja/blob/9e2c0230534b905191437d02e1ecd38ccca7f435/CHANGELOG.md?plain=1#L653) notes this is done for consistency with Jinja2. Jinja2, however, has an option to enable keeping the trailing newline in the `Environment` constructor: https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment minijinja is missing an option to keep them, which would be convenient and also great for consistency with Jinja2.

**Comment by mitsuhiko** [comment]
Yeah I think it makes sense to add that.
