### ISSUE TITLE
Capturing a global attribute in a macro leads to leaking memory

### ISSUE THREAD

**Issue by sandhose** [mitsuhiko/minijinja#358]
## Description

In some of my macros, I'm capturing globals. I noticed memory growing indefinitely in my application after each render. After analysing the allocations, it looks like some of the `Arc` created in [`Vm::build_macro`](https://github.com/mitsuhiko/minijinja/blob/f725661482369ac23af4123e741ccf00d428d9eb/minijinja/src/vm/mod.rs#L947) are never freed.

More concretely, the following template, with `{"hello": {"world": "Hello, world!"}}` as context, leaks memory:

```jinja
{%- macro foo() -%}
    {{ hello.world }}
{%- endmacro -%}

{{- foo() }}
```

## Reproduction steps

Below is a minimal example to reproduce. I also pushed this example in this repository: https://github.com/sandhose/minijinja-macro-leak/blob/main/src/main.rs

```rust
use minijinja::{value::StructObject, Environment, Value};

struct Bar;

impl Drop for Bar {
    fn drop(&mut self) {
        eprintln!("Dropping Bar");
    }
}

impl StructObject for Bar {
    fn get_field(&self, name: &str) -> Option<Value> {
        match name {
            "world" => Some(Value::from("Hello, World!")),
            _ => None,
        }
    }
}

struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping Foo");
    }
}

impl StructObject for Foo {
    fn get_field(&self, name: &str) -> Option<Value> {
        match name {
            "hello" => Some(Value::from_struct_object(Bar)),
            _ => None,
        }
    }
}

fn main() {
    let mut environment = Environment::empty();
    environment
        .add_template(
            "macro-arg",
            r#"
    {%- macro foo(arg) -%}
        {{ arg.world }}
    {%- endmacro -%}

    {{- foo(arg=hello) }}
"#,
        )
        .unwrap();

    environment
        .add_template(
            "inside-macro",
            r#"
    {%- macro foo() -%}
        {{ hello.world }}
    {%- endmacro -%}

    {{- foo() }}
"#,
        )
        .unwrap();

    environment
        .add_template("outside-macro", "{{ hello.world }}")
        .unwrap();

    for i in 0..5 {
        eprintln!("({i}) Render macro-arg:");
        let template = environment.get_template("macro-arg").unwrap();
        let res = template.render(Value::from_struct_object(Foo)).unwrap();
        assert_eq!(res, "Hello, World!");
        eprintln!();

        eprintln!("({i}) Render inside-macro:");
        let template = environment.get_template("inside-macro").unwrap();
        let res = template.render(Value::from_struct_object(Foo)).unwrap();
        assert_eq!(res, "Hello, World!");
        eprintln!();

        eprintln!("({i}) Render outside-macro:");
        let template = environment.get_template("outside-macro").unwrap();
        let res = template.render(Value::from_struct_object(Foo)).unwrap();
        assert_eq!(res, "Hello, World!");
        eprintln!();
    }

    drop(environment);

    eprintln!("Environment dropped")
}
```

Here is the output of that program: 

```
(0) Render macro-arg:
Dropping Bar
Dropping Foo

(0) Render inside-macro:
Dropping Foo

(0) Render outside-macro:
Dropping Bar
Dropping Foo

(1) Render macro-arg:
Dropping Bar
Dropping Foo

(1) Render inside-macro:
Dropping Foo

(1) Render outside-macro:
Dropping Bar
Dropping Foo

(2) Render macro-arg:
Dropping Bar
Dropping Foo

(2) Render inside-macro:
Dropping Foo

(2) Render outside-macro:
Dropping Bar
Dropping Foo

Environment dropped
```

You'll notice that when the value is passed as macro argument, or when it's used outside of the macro, it gets properly dropped at the end of the render, but when it is captured in the macro, the parent template context gets dropped, but *not* the nested value.

It doesn't even get dropped when the whole environment gets dropped

Additional helpful information:

- Version of minijinja: 1.0.8
- Version of rustc: 1.73.0
- Operating system and version: macOS 14.0 aarch64 (but also noticed leak on Linux amd64 in production)

## What did you expect

Not leak memory

**Comment by mitsuhiko** [comment]
What is likely happening here is that the closure sets up a circular reference. This needs some sort of support to capture these weakly instead. I did not check yet but I believe the `Arc` that is not freed is this one:

https://github.com/mitsuhiko/minijinja/blob/f725661482369ac23af4123e741ccf00d428d9eb/minijinja/src/vm/mod.rs#L967

The closure there holds the `hello` object which is the one we leak.

**Comment by mitsuhiko** [comment]
Specifically the problem is this. When a macro is defined it stores a closure object on the context. From then on every `StoreLocal` also persists the value on the closure. This way a macro gains a reference to itself via the closure and a cycle is created.

**Comment by sandhose** [comment]
Trying out the PR branch, it looks like macros are still leaking memory for me. I'm on macOS and struggling a bit with Instruments to do those profiles, because for some reasons the minijinja-related symbols in stack traces don't have the source file information, so I'm trying to guess out of the allocation stack traces… But it still looks like `Vm::build_macro` (and in particular the `Value::from_object` call) is the one leaking memory. How can I help you best to debug those leaks?

**Comment by sandhose** [comment]
Commenting out the store of the caller in the context ([those three lines](https://github.com/mitsuhiko/minijinja/blob/f725661482369ac23af4123e741ccf00d428d9eb/minijinja/src/vm/mod.rs#L117-L119)) does cut the leak in half, so there is probably a cycle here. I'm not using the `caller` so I could test it in my app ; in my profiles it cuts from 28MiB to 11MiB for 250 renders.

**Comment by mitsuhiko** [comment]
The linked fix is not capable of fully solving this. It's just a WIP now for me to make some progress on what the actual issue is. I know now what the problem is, but I don't have a particularly nice looking solution yet.

**Comment by mitsuhiko** [comment]
One solution might be to keep track of all created `closures` across an entire `render` call and to then break the cycles at the end.
