### ISSUE TITLE
Overload binary operators for a custom type

### ISSUE THREAD

**Issue by wolfv** [mitsuhiko/minijinja#361]
I wanted to ask wether it's currently possible to implement a custom type that would have it's own comparison operators?

Our use case is "version comparison" (which is a little different from string comparison), so that one could do:

```
python = Version("3.8")

...

{{ python >= "3.10" }}
# or
{{ python >= Version("3.10) }}
```

and get the right result.

Also totally understandable if that is out of scope. We are currently working around it with a custom function (`cmp(python, ">=3.8")`) and that works well.

**Comment by mitsuhiko** [comment]
I am leaning towards "out of scope" on this one. Not completely opposed to it, but it would require a lot of complexity everywhere. Making this explicit with a filter might be easier. Maybe a clever test would make that more readable though:

```
{{ python is matching_version(">=3.8") }}
```

**Comment by wolfv** [comment]
👍 I am going to close this for now.
