### ISSUE TITLE
Allow prepending a directory path for errors

### ISSUE THREAD

**Issue by jplatte** [mitsuhiko/minijinja#365]
## Motivation

Hi! I'm building a static site generator on top on minijinja. When it fails to render a template because of an error inside the template, it currently prints an error like

```
Error: processing `content/page.md`

Caused by:
    0: could not render include: error in "includes/sidebar.html" (in skel.html:68)
    1: undefined value (in includes/sidebar.html:4)
```

which is already not bad, but I would find it even better if the template paths (`includes/sidebar.html` and `skel.html`) would start with the path to the template directory, as that would allow Ctrl+Click on them to work in some IDE terminals, for example VSCode.

I could change my `add_template` calls to prepend this path, but this would mean that template-not-found errors would also include that prefix where it feels less appropriate and possibly misleading, and it also seems a bit less elegant (of course very subjective but maybe you get what I mean).

## Proposal

```rust
impl Error {
    fn with_template_name_prefix(self, prefix: &str) -> Self { /* ... */ }
}
```

I wouldn't mind if this method also added the prefix to template-not-found errors for consistency, as it would be trivial to only call it for rendering errors and not `get_template` errors.

**Comment by mitsuhiko** [comment]
The way Jinja2 solves this is that each template has two names: the lookup name and the source name on the file system (if available). It's a bit unfortunate that the APIs in MiniJinja don't really permit retrofitting this. A singular prefix is unlikely to work in situations where a loader considers more than one source. For now what I would recommend you to do is to actually canonicalize the names fully. You can still make the includes use the short names by configuring an appropriate path join callback (via `set_path_join_callback`).

> I could change my add_template calls to prepend this path, but this would mean that template-not-found errors would also include that prefix where it feels less appropriate and possibly misleading, and it also seems a bit less elegant (of course very subjective but maybe you get what I mean).

That wouldn't be the case. The not-found error emitted by `{% include %}` and others refers to the lookup name, not the resolved name. This means that if you have a path join callback that prepends `/foo/templates` as an example, and you look up `{% include "foo.html" %}`, and the path join callback converts it into `/foo/templates/foo.html`, the error message if `foo.html` does not exist would still emit "foo.html not found" and not "/foo/templates/foo.html not found".

You can find an example using path join callbacks in the tests: https://github.com/mitsuhiko/minijinja/blob/e543144a4b99df910744a6fdb0294a7581e801b0/minijinja/tests/test_environment.rs#L95-L116

**Comment by Hubclone** [comment]
def solution( strs):
    if not strs:
        return ""
    res = strs[0]
    i = 1
    while i < len(strs):
        while strs[i].find(res) != 0:
            res = res[0:len(res) - 1]
        i += 1
    return res

# OUTPUT:
print(solution(["flower","flow","flight"]))  # fl
print(solution(["dog","racecar","car"]))    #
print(solution(  ["ab", "a"]))

**Comment by mitsuhiko** [comment]
I'm closing this as wontfix for now. If this does not address your issue please let me know.

**Comment by jplatte** [comment]
I just realized I have another use case for (completely) overwriting the path in errors: I also use MiniJinja for templating in short strings (see https://github.com/jplatte/hinoki?tab=readme-ov-file#configuration, my SSG project is now public) and to avoid recompiling the same template string over and over again, I also want to register these templates in the environment. However, they're not stored as individual files, the only identity I have for the template source is the template source itself. So I found that I could do

```rust
env.set_loader(|tpl| Ok(Some(tpl.to_owned())));
```

and pass the template string itself to `env.get_template()` to have MiniJinja compile the template if it hasn't been seen before, or return the already-compiled template in case it's called with the same template string multiple times. I can add the necessary context for identifying where the invalid template was without help from MiniJinja, but I can't easily separate the actual error message from the unhelpful `(in <template string>:1)` bit when printing the error (AFAIK).

**Comment by mitsuhiko** [comment]
I would recommend against doing that and instead use an external caching mechanism. The environment template loader as implemented in MiniJinja has no trivial way to reset which turns it into a memory leak if you were to pass user data to it.

**Comment by jplatte** [comment]
This is in the context of a static site generator, the only case where the memory could leak in a meaningful way is in the dev-server that I plan to add.

What kind of external caching mechanism are you thinking of? `Template`s can't exist independently of the `Environment`, so I can't cache them elsewhere, right?

**Comment by mitsuhiko** [comment]
You are right that at the moment it's incredibly annoying to hold on to templates externally because of the back reference to the environment. The engine internally does not have that concern as it has an internal abstraction `CompiledTemplate` which does not yet establish that relationship. I'm not sure though if it makes sense to expose this functionality, at least in the current form.

I will try to think about a good solution here that can help with such cases.
