### ISSUE TITLE
Expose minijinja parser (as a separate crate)

### ISSUE THREAD

**Issue by jplatte** [mitsuhiko/minijinja#368]
# Motivation

I am working on a static site generator that uses minijinja. I would like to allow usage of template syntax in content, not just templates. Specifically, I'm interested in allowing macros that expand to HTML (and possibly markdown) that can be used in markdown files. Thinking about the desired semantics, I have decided that running template processing before markdown processing is a no-go because the output of `{{ template expression }}` blocks would be interpreted as part of the larger document. For example the document

```md
{% for item in items %}
- {{ item }}
{% endfor %}
```

should result in a list of as many items as there are in `items`, even if one of the items is `"something\n-somethine else"`. Similarily, running markdown processing unchanged before template processing is not an option because it would break things like `Text {{ _var }} text_` (a bit convoluted, but just shrugging away the possibility of such inputs is not how I roll).

I think the way to make this work is to run markdown processing first, but fork the markdown parser I'm using (`pulldown_cmark`) and "teach" it to detect `{{ }}`, `{% %}` and `{# #}` blocks, then re-emit them verbatim without looking for markdown syntax inside before running minijinja on the pre-processed input. However, AFAIU there is no straight-forward way to do the "detect minijinja blocks" part: It requires proper parsing to know that `{{ function("}}") }}` ends at the second (unquoted) double brace.

# Proposal

I'd like to split minijinja's parser into a separate crate. I haven't looked at the implementation yet but would assume that this

- is not horribly complicated
- is not a breaking change
- does not hinder forwards compatibility
  - … because the parser would be a private dependency of `minijinja`
  - … which would mean people like me who want to use both together would need to set up something like [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) to ensure the parser they use directly is the same as the one used by minijinja, but that doesn't seem like a big deal

If you agree and like this proposal, I would be happy to put in the leg work.

**Comment by mitsuhiko** [comment]
I'm not horribly opposed to it, but I'm also not sure if this is the right course of action at the moment. You can already funnel out the parser via the `unstable_machinery` feature. I cannot guarantee semver compatibility, but that's generally something I would not like to have on a parser / the internals until I feel very strongly about that I can commit to some stability here.

**Comment by jplatte** [comment]
Oh, I didn't know about the `unstable_machinery` feature. That's very helpful! Is it intentionally not mentioned in the documentation / left out from the docs.rs feature set?

**Comment by mitsuhiko** [comment]
Yes. It's intentionally not documented currently. I'm basically stabilizing it via people that have needs independent of the semver stability. I am thinking of eventually exposing it via a separate crate once I think it's on a reasonable state.

**Comment by mitsuhiko** [comment]
I'm closing this for now.
