### ISSUE TITLE
clap_builder error for --no-default-features build of minijinja-cli

### ISSUE THREAD

**Issue by paolobarbolini** [mitsuhiko/minijinja#370]
## Description

I've installed minijinja-cli with no default features

## Reproduction steps

1. `cargo install minijinja-cli --no-default-features --version 1.0.9 --locked`
2. `minijinja-cli`
3. Error ```thread 'main' panicked at /home/paolo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.22/src/parser/matches/arg_matches.rs:181:17:
arg `repl`'s `ArgAction` should be one of `SetTrue`, `SetFalse` which should provide a default```

Additional helpful information:

- Version of minijinja-cli: `1.0.9`
- Version of rustc: `rustc 1.75.0-nightly (a2f5f9691 2023-11-02)`
- Operating system and version: `Arch Linux`

## What did you expect

I expected it to work.

**Comment by mitsuhiko** [comment]
I'm not sure what's going on but I cannot reproduce this. I wonder if this in issue with nightly.

**Comment by paolobarbolini** [comment]
I've also tried on stable `cargo 1.73.0 (9c4383fb5 2023-08-26)` and it still happens :thinking:

**Comment by mitsuhiko** [comment]
I am super confused how this is happening. I do not have a linux machine but it doesn't happen to me on windows or macos.

**Comment by mitsuhiko** [comment]
Nevermind. I can reproduce.
