### ISSUE TITLE
Feature suggestion: Timestamp formatting filter

### ISSUE THREAD

**Issue by jplatte** [mitsuhiko/minijinja#378]
It would be nice if something like `{{ date_var | date("%d.%m.%Y") }}` could be used to convert an ISO8601 date to a localized version.

Prior art: [Tera's `date` filter](https://keats.github.io/tera/docs/#date), [Liquid's `date` filter](https://shopify.github.io/liquid/filters/date/)

**Comment by mitsuhiko** [comment]
This exists in `minijinja-contrib`: [`datetimeformat`](https://docs.rs/minijinja-contrib/1.0.10/minijinja_contrib/filters/fn.datetimeformat.html).

**Comment by jplatte** [comment]
Oh, I didn't know about `minijinja-contrib`. Thanks for the quick reply!
