### ISSUE TITLE
Feature request: Inline replacement

### ISSUE THREAD

**Issue by yonas** [mitsuhiko/minijinja#404]
## Description

It would be nice if minijinja could make inline replacements. For example, specifying `--inline` would modify the template file with the final output.

**Comment by mitsuhiko** [comment]
I would need more information here. I'm not sure I understand the feature request here.

**Comment by yonas** [comment]
@mitsuhiko If you have
```
$ cat input.txt
Hello {{ name }}
```

Running something like `minijinja --inline input.txt -D name="Test" output.txt` would result in
```
$ cat output.txt
Test
```

**Comment by mitsuhiko** [comment]
How is this different from what you can already do?

```
minijinja-cli input.txt -D name="Test" > output.txt
```

**Comment by yonas** [comment]
@mitsuhiko Correction - if you have
```
$ cat input.txt
Hello {{ name }}
```

Running something like `minijinja --inline input.txt -D name="Test"` would result in
```
$ cat input.txt
Test
```

**Comment by mitsuhiko** [comment]
Sorry i absolutely do not comprehend. How does

```
Hello {{ name }}
```

Turn into

```
Test
```

?

What it sounds in a way to me is that you want to replace the template file in-place? I'm struggling to understand why you would want that. But even if you do, you can do this:

```
minijinja-cli input.txt -D name="Test" > input.txt
```

**Comment by yonas** [comment]
@mitsuhiko When I run `minijinja-cli input.txt -D name="Test" > input.txt`, `input.txt` is empty.

Can you post the results of `cat input.txt`? I believe you'll find it is empty.

**Comment by mitsuhiko** [comment]
Yes you are right. If the filenames match then the shell will truncate the file before running. So the ask here is basically to let MiniJinja write to a file other than stdout itself so that the output could be placed to the same file as the input file?
