### ISSUE TITLE
feat request: store undefined variable names in the state.

### ISSUE THREAD

**Issue by yacir** [mitsuhiko/minijinja#423]
the idea is to catch the undefined variable names and make them accessible true the State

```rust 
Returns a list of the names of the undefined variables.
pub fn undefined_variables(&self) -> Vec<&str>
```

could be really helpful to better handle errors and helping to fix template errors easily
```rust 
let tmpl = env.template_from_str("Hello {{ what }} {{where}}!").unwrap();
let (rv, state) = tmpl.render_and_return_state(context!{ what => "World" }).unwrap();
assert_eq!(state.undefined_variables().len(), 1);
```

**Comment by mitsuhiko** [comment]
This is unlikely to be in scope for MiniJinja but you can already use the APIs available to dynamically accomplish the same thing: https://github.com/mitsuhiko/minijinja/tree/main/examples/undefined-tracking
