### ISSUE TITLE
Binary (and octal and hexadecimal) integer literals

### ISSUE THREAD

**Issue by inducer** [mitsuhiko/minijinja#428]
For a specific compatibility use case, I would be interested in MiniJinja supporting Python's `0b10101` (and, for consistency, `0xabcdef` and `0o1234`) integer literals. The relevant code seems easy enough to hack:

https://github.com/mitsuhiko/minijinja/blob/68f6a2d5d05dc34e95e914f4c56c2608d623a366/minijinja/src/compiler/lexer.rs#L218-L263

I would be happy to work on a PR if there is upstream interest. Is there? :slightly_smiling_face:

**Comment by mitsuhiko** [comment]
Yeah. Happy to accept a PR on this.

**Comment by inducer** [comment]
Thank you very much! Is 1.0.3 planned to be released soon? (Not trying to nag, though it would obviously help me.) Thanks!

**Comment by mitsuhiko** [comment]
@inducer it has been released

**Comment by inducer** [comment]
[PyPI](https://pypi.org/project/minijinja/#history) only seems to know about 1.0.8 and lower. Or should I be looking somewhere else?

**Comment by mitsuhiko** [comment]
@inducer this is fixed now.
