### ISSUE TITLE
[Python] Consider providing rendering API with separate context object

### ISSUE THREAD

**Issue by inducer** [mitsuhiko/minijinja#429]
IIUC, right now, all template rendering functionality takes the context as `**kwargs`. This leads to at least two not-so-desirable outcomes:

- The namespace between arguments to the rendering function and context variables becomes shared. For example, if a context contains an identifier `name` when passed to `render_named_str`, an error will result, needlessly.
- Any keyword argument added to rendering functions will potentially break compatibility.

**Comment by mitsuhiko** [comment]
I cannot reproduce this:

```
>>> from minijinja import Environment
>>> Environment().render_str('{{ name }}', name=42)
'42'
>>> Environment().render_str('{{ name }', 'blah.txt', name=42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
minijinja.TemplateError: syntax error: unexpected `}}`, expected end of variable block (in blah.txt:1)
---------------------------------- blah.txt -----------------------------------
   1 > {{ name }
     i         ^ syntax error
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
No referenced variables
-------------------------------------------------------------------------------
```

As you can see they are declared as positional only arguments so they should not clash.
