### ISSUE TITLE
Python binding?

### ISSUE THREAD

**Issue by peterdemin** [mitsuhiko/minijinja#43]
Given that Rust implementation should be faster, would it be possible to have a Python binding for the Rust library?

**Comment by mitsuhiko** [comment]
It is possible but I strongly doubt that the Rust implementation would be faster. Even in Rust I'm not sure if the engine would be faster. The reason for this is that any structure first needs to be send through serde to be available as a runtime reflected object in the engine. In theory that transformation step might not be necessary for a Python binding if dynamic objects are used but I'm not sure how this would work with lifetimes at the moment.

It would be interesting to try to benchmark this though.

**Comment by mitsuhiko** [comment]
I'm unlikely going to work on this and am thus closing this issue.
