### ISSUE TITLE
Embed tag (from twig)

### ISSUE THREAD

**Issue by j0lol** [mitsuhiko/minijinja#436]
I was looking for a good way to have reusable elements with block overrides (somewhat like a component?) and I couldn't find a good way to do it (though I may have missed something..) It looks like twig has exactly what I was looking for, but sadly it's in PHP! It would be nice to have something similar in minijinja for this use case. I know macros could technically be used for this, but I personally don't think it would be as ergonomic as the embed tag.

 https://twig.symfony.com/doc/3.x/tags/embed.html
 
 (here's an example from their docs)

 ```jinja
 {% embed "teasers_skeleton.twig" %}
    {# These blocks are defined in "teasers_skeleton.twig" #}
    {# and we override them right here:                    #}
    {% block left_teaser %}
        Some content for the left teaser box
    {% endblock %}
    {% block right_teaser %}
        Some content for the right teaser box
    {% endblock %}
{% endembed %}
```

**Comment by mitsuhiko** [comment]
I can see the appeal but I do not want to completely depart from what Jinja2 does as well. This might be something to bring up in the jinja2 repo to see if there is appetite for that. I don't want to run ahead and start building features into the engine here which are going significantly beyond what Jinja2 itself does.
