### ISSUE TITLE
Support adding methods to objects

### ISSUE THREAD

**Issue by EricLBuehler** [mitsuhiko/minijinja#438]
Hello all,

I am using `minijinja` to implement chat templating for LLMs. However, some templates call the `.strip()` method and I cannot find a way to inject this object. Is this possible to do? Thank you!

**Comment by mitsuhiko** [comment]
It's quite intentional that methods of Python objects are not exposed. For the same reason `|items` is used rather than `.items()` and a filter has been added to Jinja2 to match the two engines. For `.strip()` there is a `|trim` filter which has the same behavior.

```jinja2
{{ " foo "|trim }}
```

**Comment by mitsuhiko** [comment]
See also https://github.com/pallets/jinja/issues/1561

**Comment by mitsuhiko** [comment]
On further reconsideration I do think it might be useful to add a callback to the environment so that someone could on their own fill in the blanks if they have a need.

**Comment by mitsuhiko** [comment]
I added a hook now in #441 which should help if you want to make this work.
