### ISSUE TITLE
Suggestion: support {% macro %}

### ISSUE THREAD

**Issue by emi2k01** [mitsuhiko/minijinja#44]
My main use case for this is displaying recursive data. I think currently the only way to display recursive data with minijinja is by flattening it in rust code. Recursive `include` doesn't work either.

Would this feature still be in scope of minijinja? I'm not sure if the mini is because it doesn't support all features of jinja or because it doesn't plan to.

**Comment by emi2k01** [comment]
😳😳😳 Recursive `include` works. I got an `UndefinedError` and I thought it was literally an error that the developer hadn't defined. I was using `dbg!` so I didn't get the `Display` message.

With recursive includes I don't see much point in macros tbh

**Comment by mitsuhiko** [comment]
One additional note is that with the next release version the `recurse` modifier on loops will start working like in Jinja2.

**Comment by user4815162342** [comment]
Would you consider reopening this issue as a feature suggestion? I don't need macros for recursion, but i still think it's a good idea.  

My own use case is being able to keep all of the template code in one file and still have code-reuse. My program then only has to worry about adding one file to the environment.

**Comment by joshuataylor** [comment]
Hi!

I love minijinja so far, it's excellent. The thought process behind `set_source` for dynamic templates is excellent, and there are some very sensible design decisions that make this library really good.

I'm building an application that takes in SQL files which have jinja in them, and "compiles" it into SQL.

dbt is a popular tool in the Data Engineering space which allows you to build models (what dbt calls views/tables) using SQL+jinja. It's really easy to use as it's "just SQL", sprinkled with jinja. You can see the docs [here](https://docs.getdbt.com/docs/building-a-dbt-project/jinja-macros) around how they use macros extensively. They also have a [dbt-utils](https://github.com/dbt-labs/dbt-utils) project as well, which has cross-database macros you can use. Very handy!

In our own projects we use a few macros to help with repetitive SQL snippets.

IMHO for this usecase, having a macro like this:
```
{% macro something(name, bar) -%}
```

We could map name/bar to [Value](https://docs.rs/minijinja/latest/minijinja/value/struct.Value.html).

--

As a side note, I'm not sure if macros should belong in this repository or if it should live in another crate. At the very least it should be feature gated.

It's a complicated topic (as you noted) but having a basic version that only supports basic types or something could be a quick win?

What are your thoughts around this? (I'll probably end up just having a basic version of macro support in the above, and maybe make a crate if it's useful (my work will be opensource anyway :shrug:?)

**Comment by mitsuhiko** [comment]
The "problem" with `{% macro %}` is that the design in Jinja2 leverages Python's closures which is now something part of the design. This means that implementing macros requires also emulating Python's closure semantics and that's quite a bit of work for "just" that feature. I'm not ruling it out, but it's more work than many other features.

Additionally it requires implementing imports too which I could get away without so far.

**Comment by joshuataylor** [comment]
Yep makes sense! Thanks for the explanation.

**Comment by joshuataylor** [comment]
I am currently testing and implementing macro support, with the intention of (almost, given [COMPABILITY.md](https://github.com/mitsuhiko/minijinja/blob/main/COMPATIBILITY.md#python-methods)) fully supporting dbt macros out of the box.

It's led to finding some interesting compatibility issues (sorry for the spam!), but I'm trying to work out a nice way to add macros, similar to way sources work, which will allow flexibility where a user can both add macros to their templates if they wish, but can also use `env.add_macro()` or a macro loader like (ignore the placeholder name):
```rust
    env.set_macro_source(MacroSource::with_loader(|name| {
        if name == "mymacro" {
            Ok(Some("...".into()))
        } else {
            Ok(None)
        }
    }));
```

**Comment by mitsuhiko** [comment]
Rather than making a macro specific source I would add a dynamic callback for any global. Macros, functions and similar things likely share the namespace anyways.
