### ISSUE TITLE
`None` Option values become the string `"none"` in templates

### ISSUE THREAD

**Issue by nfagerlund** [mitsuhiko/minijinja#444]
## Description

I'm not sure if this is considered a "bug" or not, but it definitely doesn't match what I expected or what I want. 

Here's the practical use case: 

- I've got a `Bookmark` struct that is `Serialize`. Its `display_name` field is `Option<String>`. 
- In the template, I want to show the display name if available, and fall back to another identifier if not. 
- So I figure: `{{b.display_name | default(b.url)}}` — the None variant should end up as falsy/undefined, and the `default` filter should handle the rest. 

But, no: it ends up displaying the text `none` instead of falling back to something useful. And naturally I don't want to do a string comparison check for the literal "none", because the app logic doesn't consider that an invalid name for a bookmark.

Is this happening because [the fmt::Display impl for Value writes "none"](https://github.com/mitsuhiko/minijinja/blob/045d6a0f7ee1ea9cb4aa7725bc8fb1c39ab1d90b/minijinja/src/value/mod.rs#L518) in the case of ValueRepr::None? Or is it somewhere else in the vm?

## Reproduction steps

Most minimal repro case: 

```rust
fn main() {
    let ctx = minijinja::value::Value::from_serializable::<Option<&str>>(&None);
    println!("{}", minijinja::render!("{{stuff}}", stuff => ctx));
}
```

Output: 

```
none
```

Additional helpful information:

- Version of minijinja: 1.0.12
- Version of rustc: 1.76.0
- Operating system and version: macos 14.2.1 (arm64)

## What did you expect

I expected minijinja to do one of the following: 

- Just conflate `None` with "undefined", so they behave identically and can't be distinguished from each other.
- Preserve `None` as a first-class type in templates distinct from "undefined", but treat them similarly in constructs like the `default` filter that operate on a generic concept of "nothing". 

Alternately: I wouldn't say I'd _expect_ the following behavior, and I would have found it annoying, but it at least would have looked like the type of jank I've met in template languages before: 

- Convert `None` to an empty string (`""`).

I think using the literal string "none" is pretty much the maximally surprising thing it could have done! 

## Workarounds

It looks like I can forcibly convert a None to an absent value at the Serialize level via the standard serde macros:

```rust
#[derive(Serialize)]
pub struct Bookmark {
    // ...
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}
```

But that has effects in other places that use Serialize (like json), and I haven't yet decided whether those interfaces can cope with conflating absent and null. (It's probably fine.) I guess I could use `serializing_for_value` in a custom Serialize impl, but I don't like how that feels at all, so it'd be a last resort.

**Comment by mitsuhiko** [comment]
This is intentional. However not everybody likes this behavior which is why you can trivially customize it with [`set_formatter`](https://docs.rs/minijinja/latest/minijinja/struct.Environment.html#method.set_formatter):

```rust
use minijinja::{Environment, Value, escape_formatter};

let mut env = Environment::new();
env.set_formatter(|out, state, value| {
    escape_formatter(
        out,
        state,
        if value.is_none() {
            &Value::UNDEFINED
        } else {
            value
        },
    )
});
```

**Comment by nfagerlund** [comment]
Whoa, that's pretty wild for an intentional default! But, thank you for pointing out the formatter as an elegant point to perform that translation, that's very helpful.

**Comment by mitsuhiko** [comment]
Yeah, the right solution would be then to change the behavior of `default` by making a function that handles `none`. I might add an example that demonstrates this.
