### ISSUE TITLE
How to use `lstrip_blocks`

### ISSUE THREAD

**Issue by EricLBuehler** [mitsuhiko/minijinja#446]
Hello all,

I am using minijinja for chat templating, and need th e `lstrip_blocks` and/or `trim_blocks` functionality. As can be seen [here](https://github.com/huggingface/transformers/blob/76a33a10923ccc1074917f6b6a1e719e626b7dc9/src/transformers/tokenization_utils_base.py#L1842), this is passed to the Environment. Is there a way to do this with minijinja? I would appreciate any help!

**Comment by mitsuhiko** [comment]
Neither one of those flags are supported today.

**Comment by EricLBuehler** [comment]
Would there be a way to implement this in minijinja? Perhaps I misunderstood, I thought they are supported on the Python side.

**Comment by mitsuhiko** [comment]
This was implemented by #447

**Comment by EricLBuehler** [comment]
Thank you!
