### ISSUE TITLE
Suggestion: allow mutation through `set_function`

### ISSUE THREAD

**Issue by Actimia** [mitsuhiko/minijinja#449]
We are looking into ways of setting metadata from templates that are later read by the surrounding code. Our best attempt so far includes something like

```
    let mut env = Environment::new();
    let mut map: BTreeMap<String, String> = BTreeMap::new();
    env.add_function("set_test", move |x: String| {
        map.insert(x, "test".into());
    });
```

But this does not work, due to `add_function` only accepting `Fn` and not `FnMut`.

Is there a better way of doing this, or are we doing something wrong?

**Comment by mitsuhiko** [comment]
@Actimia you can do that if you put the map into an `Arc<Mutex<BTreeMap<...>>`. Note however that this means that one template will leak into another one if the `Environment` is shared:

```rust
use minijinja::{Value, Environment};
use std::sync::{Arc, Mutex};
use std::collections::BTreeMap;

fn main() {
    let mut env = Environment::new();
    env.add_template("hello.txt", "{% do set_test('x') %}{{ get_test('x') }}").unwrap();
    env.add_template("hello2.txt", "{{ get_test('x') }}").unwrap();
    let map: Arc<Mutex<BTreeMap<String, Value>>> = Default::default();
    {
        let map = map.clone();
        env.add_function("set_test", move |x: String| {
            map.lock().unwrap().insert(x, Value::from("test"));
        });
    }
    {
        let map = map.clone();
        env.add_function("get_test", move |x: String| -> Value {
            map.lock().unwrap().get(&x).cloned().unwrap_or_default()
        });
    }
    let template = env.get_template("hello.txt").unwrap();
    println!("{}", template.render(()).unwrap());
    let template = env.get_template("hello2.txt").unwrap();
    println!("{}", template.render(()).unwrap());
}
```

This will print `test` twice. You can do stuff like this better if you actually pass functions with side-effects into `render()` within a `context!` as that way you can ensure that the data does not outlive the state. Another option would be to stash the data into a thread local instead which gets manually cleared at the end of every render. There might be more ways.
