### ISSUE TITLE
Latest releases not on PyPI

### ISSUE THREAD

**Issue by inducer** [mitsuhiko/minijinja#451]
According to [Github tags](https://github.com/mitsuhiko/minijinja/tags) and [Releases](https://github.com/mitsuhiko/minijinja/releases), 1.0.15 and 1.0.16 seem like they're out, but it looks like they are missing from the Python package index:

https://pypi.org/project/minijinja/#history

**Comment by mitsuhiko** [comment]
Not every release is uploaded to pypi, but i made sure that 1.0.16 is up on there.
