### ISSUE TITLE
2.0: Separate Iterators from Sequences

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/minijinja#454]
With MiniJinja 2.0 it should become possible to separate out iterators properly from sequences.

* Introduce `ObjectRepr::Iterator`
* Introduce `ValueKind::Iterator`

Relates to:
* #457

**Comment by SergioBenitez** [comment]
I think it would be a mistake to introduce another object-like value. The idea behind Objects 2.0 was to unify the value interfaces for anything object-like, which I would argue fits an iterator. Separating the two defeats that notion. There are objects which produce enumerations that are iterators, so you already need to deal with not knowing the size of the enumeration in an `Object`. What else would an `Iterator` value add?

**Comment by mitsuhiko** [comment]
> The idea behind Objects 2.0 was to unify the value interfaces for anything object-like, which I would argue fits an iterator

There is a fundamental difference between an iterator and a sequence. A sequence has a length and can be indexed, an iterator cannot. There might be some iterators which are reversible and it's reasonable to express that. An iterator is still an object, but it's not a sequence.
