### ISSUE TITLE
2.0: Align iteration protocol with MiniJinja 1

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/minijinja#456]
Currently the iteration protocol for an `Object` has two separate interfaces. `values()` which yields values and `iter()` which yields key and values. It should be changed so that there is just `iter()` which yields keys for maps and values for sequences and iterators.

**Comment by SergioBenitez** [comment]
Note that this is what `Value::try_iter()` returns. I don't think it's necessary to introduce this at the `Object` level.

**Comment by mitsuhiko** [comment]
I think the challenge of the current iteration protocol is that it's a bit odd to work with. The enumerator basically always only yields the "keys" and the value then comes from `get_value`. For real iterators that's sort of annoying to implement or at least sort of odd. At the same time it's nice that it's as far as `Enumerator` is concerned the behavior is consistent.

For #457 however this protocol is odd.

**Comment by mitsuhiko** [comment]
I wonder if the way to square this is to change `Object` to have an optional explicit, separate iteration method. If not implemented the default iteration behavior from `Enumeration` kicks in, otherwise the object needs to yield values like the for loop expects. It would only be used for real iterators and cases like `from_object_iter`.

```rust
pub trait Object: fmt::Debug {
    fn enumeration(self: &Arc<Self>) -> Enumeration {
        Enumeration::Empty
    }

    fn get_value(self: &Arc<Self>) -> Option<Value> {
        None
    }

    fn try_iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value>>> {
        None
    }
}
```

**Comment by mitsuhiko** [comment]
I tried this now and I quite like it. I did no play this out to the end yet but I think the following logic might work quite well in practice:

* `Object::enumeration` returns an `Enumeration` as today. The following two new values get added: `Enumeration::NonEnumerable` to indicate an object has no natural enumeration (see also #459)
* `Object::try_iter` can be implemented by `NonEnumerable` (or any other object for that matter) to directly return a non reversible iterator.
* `Enumeration::into_iter` is removed and replaced by `Enumeration::try_into_iter` which fails for `NonEnumerable`
* `EnumerationIter` gains a `try_reverse` method which flips the enumerator around if possible, addressing #455

**Comment by SergioBenitez** [comment]
I don't understand what `NonEnumerable` means. If an object is `NonEnumerable`, should its `custom_iter()` method always return `None`? Should it really be `enumeration() -> Option<Enumeration>`?

I also don't understand (and I didn't before either) what `ObjectRepr::Plain` means. What is the need for such objects? How are they different from maps or seqs?

Finally, it continues to feel to me that the interface here isn't quite right. There's simultaneously odd conflation and separation between wanting to know how to serialize the object and how to enumerate its keys and values. I had considered a similar idea, of allowing the object to tell you how to iterate over them, but seeing the implementation I'm not sure it's quite right.

From what I can gather, the kernel of the issue is in knowing whether an object sees itself as a collection of keys _and_ values or of only values. In particular, "sequences" seem to have keys in the form of indices, but the keys are tossed away during iteration. Conversely, "maps" have values, but the values are ignored during iteration. Finally, iteration might be reversible and infinite.

In summary, we have the following table of potential objects:

|        | Keys | Iterator | Random Access | Repr |
|---------|------|----------|---------------|------|
| Map     | Y    | Keys     | Y             | Map  |
| Seq     | Y    | Values   | Y             | Vec  |
| Iter    | N    | Values   | N             | Vec  |
| Func    | N    | N/A      | N             | N/A  |

I think the key insight here is that the iteration behavior is what determines the representation. With this in mind, I'm proposing the following interface to replace all of `repr()`, `custom_iter()`, and the current `enumeration()`:

```rust
enum Enumeration {
    Keys(Iteration),
    Values(Iteration),
}

pub enum Iteration {
    Owned(Vec<Value>),
    Static(&'static [&'static str]),
    Iterator(Box<dyn Iterator<Item = Value> + Send + Sync>),
    DoubleEndedIterator(Box<dyn DoubleEndedIterator<Item = Value> + Send + Sync>),
    Sized(usize),
}

fn enumeration(self: &Arc<Self>) -> Option<Enumeration>;
```

A `HashMap` returns an `Enumeration::Keys`, a `Vec` and `Iterator` return an `Enumeration::Values`, and the rest return `None`. `HashMap` and `Vec` implement `get_value()`, since they allow random access, while the other do not.

An alternative isomorphic interface separates the two:

```rust
enum Enumerable {
    Keys,
    Values,
}

enum Enumeration {
    Owned(Vec<Value>),
    Static(&'static [&'static str]),
    Iterator(Box<dyn Iterator<Item = Value> + Send + Sync>),
    DoubleEndedIterator(Box<dyn DoubleEndedIterator<Item = Value> + Send + Sync>),
    Sized(usize),
}

fn enumerable(self: &Arc<Self>) -> Option<Enumerable>;

fn enumeration(self: &Arc<Self>) -> Option<Enumeration>;
```

**Comment by mitsuhiko** [comment]
> I don't understand what `NonEnumerable` means. If an object is `NonEnumerable`, should its `custom_iter()` method always return `None`? Should it really be `enumeration() -> Option<Enumeration>`?

As it exists at the moment, `enumeration()` returns the natural enumeration of the object. It does not only affect the enumeration. A `NonEnumerable` object has two purposes: it either is an object that just does not enumerate at all, but as far as truthy checks are concerned is not empty. It does not directly say what should happen to `custom_iter`. An object is iterable if it either a) has an `Enumeration` that is not `NonEnumerable` or b) has a `custom_iter`.

Having two conflicting iteration protocols is not completely out of the ordinary. Compare for instance the natural iterator behavior of objects in Python:

```python
>>> class X:
...  def __getitem__(self, x):
...   if x > 10:
...    raise IndexError
...   return x
...
>>> list(X())
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

vs explicit iteration:

```python
>>> class X:
...  def __getitem__(self, x):
...   raise IndexError
...  def __iter__(self):
...   yield 42
...
>>> list(X())
[42]
```

> I also don't understand (and I didn't before either) what `ObjectRepr::Plain` means. What is the need for such objects? How are they different from maps or seqs?

As mentioned somewhere else already plain objects currently cause a lot of pain in the engine because some things accidentally treat them as maps. Example for plain objects are for instance any boxed function. For instance in 1.x if you `{{ debug|tojson }}` you end up with an empty dict, whereas in 2.x now you correctly get a stringified representation of that function as it was intended. A plain object is just an object that exists, but it does not behave as either map or sequence. Likewise a macro should also not behave like a `map`. That it does is an accident of the implementation.

> Finally, it continues to feel to me that the interface here isn't quite right. There's simultaneously odd conflation and separation between wanting to know how to serialize the object and how to enumerate its keys and values. I had considered a similar idea, of allowing the object to tell you how to iterate over them, but seeing the implementation I'm not sure it's quite right

I'm not entirely sure yet either but I want to keep exploring until it feels right.

> From what I can gather, the kernel of the issue is in knowing whether an object sees itself as a collection of keys _and_ values or of only values. In particular, "sequences" seem to have keys in the form of indices, but the keys are tossed away during iteration. Conversely, "maps" have values, but the values are ignored during iteration. Finally, iteration might be reversible and infinite.

I think a better way to reason about it is to recognize that the underlying iteration and object protocol is basically what Python does since it inherits the semantics from Jinja2. While it looks like from your table that iteration defines if an object is a sequence, a map or something else, I don't believe this to be a general truth. I think this might be the more correct table:

|            | Iterator | Length | Random Access | Print Repr | To JSON |
|------------|----------|--------|---------------|------------|---------|
| Map        | Keys     | Y      | Y             | Map        | Object  |
| Seq        | Values   | Y      | Y             | Vec        | Array   |
| Iter Once  | Values   | N      | N             | None       | Array   |
| Iter Twice | Values   | N      | N             | None       | Array   |
| Plain      | Values   | N      | N             | String     | String  |

`Iter Once` here is what `Value::from_iterator` creates. It just wraps an iterator. `Iter Twice` is what `Value::from_object_iter` creates. Every time you iterate, it makes a new iterator. Length is a bit of an odd thing as iterators can actually have lengths too so some of those nos are probably soft yes.

I think your proposed interface is

**Comment by mitsuhiko** [comment]
So here is my current thinking but it's not super fleshed out.  What would be the most canonical implementation of a sequence and struct?  An object has some different behaviors (iteration, looking up values by key/index, the shape for serialization and printing).  Let's just pretend for a moment that `Enumeration` does not exist at all.  How would an object be represented?  We could imagine a trait like this:

```rust
pub trait Object: fmt::Debug + Send + Sync {
    fn repr(self: &Arc<Self>) -> ObjectRepr { ... }
    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> { ... }
    fn len(self: &Arc<Self>) -> Option<usize> { ... }
    fn is_empty(self: &Arc<Self>) -> bool { ... }
    fn iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value> + Send + Sync>> { ... }
    fn call(self: &Arc<Self>, state: &State<'_, '_>, args: &[Value]) -> Result<Value> { ... }
    fn call_method(
        self: &Arc<Self>, state: &State<'_, '_>, method: &str, args: &[Value]
    ) -> Result<Value> { ... }
    fn render(self: &Arc<Self>, f: &mut fmt::Formatter<'_>) -> fmt::Result
    where
        Self: Sized + 'static,
    { ... }
}
```

This would be something like the most explicit null option where pretty much everything that defines a `Value` which is currently exposed to objects gets mapped into a direct method.  Obviously in this sort of implementation various conflicting behaviors would be possible.  But let's ignore this for a moment.  Even in that case, you probably don't want to implement everything.  What would be the minimum set of methods be that are needed to implement a map or a sequence?

For sequences (here as a fixed size point) the following would quite likely be the extreme example (ignoring `render`, `call`, etc.):

```rust
impl Object for Point {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Seq
    }

    fn len(self: &Arc<Self>) -> Option<usize> {
        2
    }

    fn is_empty(self: &Arc<Self>) -> bool {
        false
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        match key.as_usize()? {
            0 => Some(Value::from(self.x)),
            1 => Some(Value::from(self.y)),
        }
    }

    fn iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value> + Send + Sync>> {
        let mut idx = 0;
        let self_clone = self.clone();
        Some(Box::new(std::iter::from_fn(move || {
            let rv = self_clone.get_value(&Value::from(idx));
            idx += 1;
            rv
        })))
    }
}
```

Clearly this is excessive.  So we want to have less of that interface, and some of it implied.  If we wouldn't change anything of the interface, what would be a way by default implementations to get this?

* `is_empty`: this is obvious, the default implementation could be `self.len() == Some(0)`
* `iter`: there is no need to implement this for a sequence, in most cases the behavior is implied
* `len`: well this would be mandatory for sequences clearly, they need a length.

This would lead to this:

```rust
impl Object for Point {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Seq
    }

    fn len(self: &Arc<Self>) -> Option<usize> {
        2
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        match key.as_usize()? {
            0 => Some(Value::from(self.x)),
            1 => Some(Value::from(self.y)),
        }
    }
}
```

So what does this look like for custom iterables?  Let's assume here for a moment that we are talking about iterables and not iterators (eg: they can be used more than once).  In that case as a developer you would most likely really just implement `iter`:

```rust
impl Object for RangeOf10 {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Iterable
    }

    fn iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value> + Send + Sync>> {
        Some(Box::new((0..10).map(Value::from)))
    }
}
```

That wouldn't look too bad either and it has one interesting benefit.  If the length of the iterator is known ahead of creating the iterator, it could be hinted via `len` which in turn could influence `render` to print it like a sequence instead of dumping out just a `<Iterator>` string:

```rust
impl Object for RangeOf10 {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Iterable
    }

    fn len(self: &Arc<Self>) -> Option<usize> {
        Some(10)
    }

    fn iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value> + Send + Sync>> {
        Some(Box::new((0..10).map(Value::from)))
    }
}
```

Note that as far as the iteration is concerned what actually does matter is the `size_hint` of the iterator that is returned by `iter`, but the `len` is what matters before iteration starts.

So would would maps look like?  Well they would be a bit more annoying but not significantly more.  Here a map with unknown keys.

```rust
impl Object for Point {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Map
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        match key.as_str()? {
            "x" => Some(Value::from(self.x)),
            "y" => Some(Value::from(self.y)),
        }
    }
}
```

This so far is reasonable, but so far we don't know what's in it.  `len` alone is not enough here, we also need to know the keys.  So we would need this:

```rust
impl Object for Point {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Map
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        match key.as_str()? {
            "x" => Some(Value::from(self.x)),
            "y" => Some(Value::from(self.y)),
        }
    }

    fn len(self: &Arc<Self>) -> Option<usize> {
        Some(2)
    }

    fn iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value> + Send + Sync>> {
        Some(Box::new(["x", "y"].into_iter().map(Value::from)))
    }
}
```

Now that doesn't seem entirely optimal.  In this case we would sort of want the inverse of what we did with seq where `len` is defined by the return value of the iter method (by leveraging `size_hint` for instance).  But now that clearly doesn't work because we gotta pick one to depend on the other.  It also doesn't seem entirely optimal that you now need to return a manual iterator this way, seems cumbersome.  Because maps are also more common than vectors, it would only be reasonable to optimize the interface for those.

My takeaway from this is that there is some sort of relationship of the iteration to the length, but not necessarily to the shape of the object.  I believe that the shape of the object is inherent.  With or without iteration, by holding it you want to know if it behaves more like a sequence or like a map (or some plain object that is neither one of those things).

This is where `Enumeration` is kind of helpful, because it carries that length.  So what if we were to make one change to that interface to replace the trio of `len`, `iter` and `is_empty` in the following way:

```rust
pub trait Object: fmt::Debug + Send + Sync {
    fn enumerate(self: &Arc<Self>) -> Option<Enumerator> { ... }
}

#[non_exhaustive]
enum Enumerator {
    Sequential(usize),
    Iter(Box<dyn Iterator<Item = Value> + Sync + Send>),
    Str(&'static [&'static str]),
    Values(Vec<Value>),
}
```

Now the enumerator no longer actually defines iteration directly, instead if's just an abstract utility that expresses how the object is to be enumerated.  The iterator that is created for that enumeration is only in the case of `Iter` be directly exposed.  As such the `Enumerator` really is just something that assists the engine in enumeration but it can also tell the length either directly or by `size_hint` of the embedded iterator before iteration.  The above examples would then turn into this:

```rust
impl Object for Point {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Seq
    }

    fn enumerate(self: &Arc<Self>) -> Option<Enumerator> {
        Some(Enumerator::Sequential(2))
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        match key.as_usize()? {
            0 => Some(Value::from(self.x)),
            1 => Some(Value::from(self.y)),
        }
    }
}

impl Object for Point {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Map
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        match key.as_str()? {
            "x" => Some(Value::from(self.x)),
            "y" => Some(Value::from(self.y)),
        }
    }

    fn enumerate(self: &Arc<Self>) -> Option<Enumerator> {
        Some(Enumerator::Str(["x", "y"]))
    }
}

impl Object for RangeOf10 {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Iterable
    }

    fn enumerate(self: &Arc<Self>) -> Option<Enumerator> {
        Some(Enumerator::Iter(Box::new((0..10).map(Value::from))))
    }
}
```

Then the object trait could look like this (including default impls but again without `render`, etc.):

```rust
pub trait Object: fmt::Debug + Send + Sync {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        ObjectRepr::Map
    }

    fn get_value(self: &Arc<Self>, key: &Value) -> Option<Value> {
        None
    }

    fn enumerate(self: &Arc<Self>) -> Option<Enumerator> {
        None
    }

    fn len(self: &Arc<Self>) -> Option<usize> {
        match self.enumerator()? {
            Enumerator::Sequential(l) => Some(l),
            Enumerator::Iter(iter) => match iter.size_hint() {
                (lower, Some(upper)) if lower == upper => Some(upper),
                _ => None
            },
            Enumerator::Str(s) => Some(s.len()),
            Enumerator::Values(v) => Some(v.len()),
        }
    }

    fn is_empty(self: &Arc<Self>) -> bool {
        self.len() == Some(0)
    }

    fn iter(self: &Arc<Self>) -> Option<Box<dyn Iterator<Item = Value> + Send + Sync>> {
        match self.enumerator()? {
            Enumerator::Sequential(l) => {
                let mut idx = 0;
                let self_clone = self.clone();
                Some(Box::new((0..l).map(move |idx| {
                    self_clone.get_value(&Value::from(idx));
                })))
            }
            Enumerator::Iter(iter) => Some(iter),
            Enumerator::Str(s) => Some(s.into_iter().map(Value::from)),
            Enumerator::Values(v) => Some(v.into_iter()),
        }
    }
}
```

And in that case, `iter`, `is_empty` and `len` could either remain on `Object` or be moved as hidden behavior into `Value` entirely.

**Comment by mitsuhiko** [comment]
I still think there is an argument to be made that `Option<Enumerator>` really wants to be just `Enumerator` but with an extra `NonEnumerable` option.  It might make for a slightly nicer API for the user as one does not have to wrap it in an extra `Some` most of the time.  I also think that it might make the distinction between `Empty` and `NonEnumerable` smaller.

**Comment by mitsuhiko** [comment]
I merged this for now.  An interesting option would be to flip the behavior of `repr` and `enumerate` around.  That would mean that `Seq` in theory could be detected by `Enumerator::Seq` as originally intended.

```rust
pub trait Object: fmt::Debug + Send + Sync {
    fn repr(self: &Arc<Self>) -> ObjectRepr {
        match self.enumerate() {
            Enumerator::NonEnumerable => ObjectRepr::Plain,
            Enumerator::Empty | Enumerator::Str(_) | Enumerator::Values(_) => ObjectRepr::Map,
            Enumerator::Iter(_) => ObjectRepr::Iterable,
            Enumerator::Seq(_) => ObjectRepr::Seq,
        }
    }

    fn enumerate(self: &Arc<Self>) -> Enumerator {
        Enumerator::Empty
    }
}
```

Upsides:

* `repr()` works automatically for most sequences

Downsides:

* `Empty`, `Str`, and `Values` implies `Map` which might be unexpected
* Relatively inefficient as the iterator has to be created more than once in some cases (type check before iteration)

**Comment by mitsuhiko** [comment]
I made a port of one of my own internal projects that uses objects to a great extend to this branch and I also updated the Python binding and I'm really quite pleased with how the API behaves for the most part.  It feels easier than 1.x and more flexible for sure.

**Comment by SergioBenitez** [comment]
That looks great, @mitsuhiko!

My only remaining concern is the various uses of `.collect()` when iterators might be infinite. I'm wondering if there's something better than can be done aside from exhausting the heap and crashing the program entirely. I can think of two possible approaches:

  1. Refuse to call `.collect()` unless the iterator returns an upper-bound.
    
     I think this would be a nice approach _if_ it works reliably. I'm not sure how robustly iterator adapters propagate the upper-bound of their internal iterators, however.

  2. Use a configurable fuel-like metric to track and limit collected iterator yields.

     The idea would be to add a configurable upper-limit on the number (or total bytes) of items that the user is willing to collect. Then if the limit is exhausted before the collection is completed, an error can be returned. I think this elegantly solves the problem; if the user gets an error and they know the collection is finite, they can always increase the limit.

As for performance: I wonder if the compiler will be smart enough to simply to completely remove the inner values of the `Enumerator` variants when `len()` is called. Perhaps some `#[inline(always)]` across the call chain would help? I imagine if everything is `#[inline]d` it'll be able to optimize the creation of the internal value away.

Thank you for considering all of my feedback on this -- I truly appreciate it. Excited for minijinja2 to go mainline!

**Comment by mitsuhiko** [comment]
> I think this would be a nice approach if it works reliably. I'm not sure how robustly iterator adapters propagate the upper-bound of their internal iterators, however.

There are quite a few iterators with unknown bounds in the wild, it would be quite trivial to accidentally do that (`Some(iter).into_iter().flatten()` is a good example that doesn't communicate size_hint correctly today) and then you notice that you can't even fix it in the template with `|list`.

I definitely think that having an upper bound on the collect is reasonable though I'm not sure if that would not result in accidental failures just around the breaking point where some templates work, others run into it, unless the limits are very high.

I wonder how many uses of `.collect` in the engine on iterators are remaining.  The `[:]` operator for slicing no longer collects, the main remaining case is reversing I believe.

**Comment by SergioBenitez** [comment]
> I definitely think that having an upper bound on the collect is reasonable though I'm not sure if that would not result in accidental failures just around the breaking point where some templates work, others run into it, unless the limits are very high.

Exactly: I think we go with very high limits. Something like 1GiB or more should suffice for almost every application while also being a reasonable "whoops!" deterrent.

**Comment by mitsuhiko** [comment]
I will close this as completed for now.  The separate issue with preventing large buffers I will follow up separately.
