### ISSUE TITLE
String concatenation without "+" operator

### ISSUE THREAD

**Issue by inducer** [mitsuhiko/minijinja#488]
Jinja allowed Python strings as `"abc" "def"` for concatenation at "compile time". For compatibility, it would be helpful if minijinja did as well.

**Comment by mitsuhiko** [comment]
Oh well. I completely forgot that this is a thing. Apparently there since 2008. https://github.com/pallets/jinja/commit/4778bda8312875a943e3f16df3efc5f6ffb1e586
