### ISSUE TITLE
Custom time format strings

### ISSUE THREAD

**Issue by WesleyAC** [mitsuhiko/minijinja#497]
It would be great to use custom strftime style format string with `dateformat` and the other time/date functions, or perhaps more cleanly, just make a `strftime` filter.

**Comment by WesleyAC** [comment]
Yeah — I was looking at the [minijinja_contrib filters](https://docs.rs/minijinja-contrib/latest/minijinja_contrib/filters/index.html) which support formats like `short`/`medium`/`long`/`full`/`iso`/`unix`, but don't allow fully custom formatting. Looking at the [built-in filters](https://docs.rs/minijinja/latest/minijinja/filters/index.html) I don't see any relating to time formatting.

What function should I be looking for that does custom date formatting?

**Comment by mitsuhiko** [comment]
@WesleyAC they support any of the formats from the time crate.  So you can do this:

```
{{ foo|dateformat(format="[weekday], [month repr:long] [day padding:none] [year]") }}
```

**Comment by WesleyAC** [comment]
Is this format documented anywhere?

**Comment by mitsuhiko** [comment]
@WesleyAC yes, it's documented in the time crate: https://time-rs.github.io/book/api/format-description.html
