### ISSUE TITLE
UndefinedBehavior::Strict and undefined key in mapping

### ISSUE THREAD

**Issue by ibotty** [mitsuhiko/minijinja#498]
## Description

I can reproduce my problem with `minijinja-cli`, but it happens in my own code.

## Reproduction steps

1. with input `input.json`:
```
{ "m": {} }
```
2. and template `template.j2`:
```
{% if m.key is defined %}
  {{ m.key }}
{% endif %}
```
3. and running `minijinja-cli --strict template.j2 input.json` I get
```
template error: undefined value (in [...]/template.j2:1)
----------------------------------- test.j2 -----------------------------------
   1 > {%- if m.key is defined %}
     i        ^^^^^ undefined value
   2 | {{ m.key }}
   3 | {%- endif %}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Referenced variables: {
    m: {},
}
-------------------------------------------------------------------------------
```

I would expect that the `is_defined` and `is_undefined` test would work.  I also did not find a test like `has_key` which would also solve that problem.

Is that behavior expected and intended?

## minijinja version
`minijinja-cli 1.0.20`

**Comment by mitsuhiko** [comment]
This is currently intentional but not ideal as it does not match the Jinja2 behavior for strict undefineds.  However you can solve this issue today:

```jinja2
{% if "key" in m %}
  {{ m.key }}
{% endif %}
```

**Comment by ibotty** [comment]
Ah, thank you.  I missed the `is_in` test.  Do you prefer to keep this issue open?

**Comment by mitsuhiko** [comment]
Yes. This likely should be changed.

**Comment by ibotty** [comment]
Thank you for fixing so quickly!
