### ISSUE TITLE
Add support for the `*` operator

### ISSUE THREAD

**Issue by GabrielBianconi** [mitsuhiko/minijinja#518]
Jinja2 supports e.g. `{{ ' ' * 10 }}` but that doesn't work with MiniJinja. We were able to circumvent the issue with a recursive macro, but that operator would simplify things!

```
Error: invalid operation: tried to use * operator on unsupported types string and number (in template.html:15)
```

Below is the workaround in case anyone else is having the same issue.

```
{%- macro repeat(s, times) -%}
  {%- if times >= 1 -%}
    {{ s }}
  
    {%- if times > 1 -%}
      {{ repeat(s, times - 1) }}
    {%- endif -%}
    
  {%- endif -%}
{%- endmacro -%}

{{ repeat("abc", 4) }}
```

**Comment by mitsuhiko** [comment]
That makes sense. Would also need to support sequences and potentially iterators. I will look into it.

**Comment by GabrielBianconi** [comment]
Thanks!
