### ISSUE TITLE
Support for the boolean() filter

### ISSUE THREAD

**Issue by bertjwregeer** [mitsuhiko/minijinja#52]
As I am going through and trying to use this, it would be great if there was a standard boolean filter that takes in text and returns true for values like:

- yes
- true
- True

and then `false` for string values like this:

- false
- False
- no

Although I am not sure if that is what the Jinja2 filter does, or if I am thinking of the ansible `bool` filter instead...

**Comment by mitsuhiko** [comment]
I will add this for compatibility but in practical terms it's rarely useful as `{% if foo %}` is the same as `{% if foo|bool %}`. I do see it being useful for ansible type uses though and it will become more useful if we do #50.
