### ISSUE TITLE
Break/continue support

### ISSUE THREAD

**Issue by Rocketknight1** [mitsuhiko/minijinja#557]
Hi, Matt from Hugging Face here! We were experimenting with adding `break` and `continue` via the `loopcontrols` extension in Jinja. Is this something that could be added to `minijinja` as well, or would that be very difficult?

**Comment by mitsuhiko** [comment]
No, I'm open to adding this.  I think I would flag it behind a feature like we do with macros.  Not sure if this needs to be something that is controlled on the environment.

**Comment by Rocketknight1** [comment]
Wow, that was fast. Thank you!

**Comment by fortzi** [comment]
@mitsuhiko Can this be made available in minijinja-py? 🙏

**Comment by mitsuhiko** [comment]
Good point. That was an oversight.
