### ISSUE TITLE
Unable to set an undefined_behavior for a minijinja Enviroment in Python

### ISSUE THREAD

**Issue by zdxerr** [mitsuhiko/minijinja#560]
## Description
I am unable to set an undefined_behavior for a minijinja Enviroment in Python.

I get 
RuntimeError: invalid value for undefined behavior
if I use a string.

```
env = minijinja.Environment(
    keep_trailing_newline=keep_trailing_newline,
    undefined_behavior="Lenient",
)
```

**Comment by mitsuhiko** [comment]
The valid values for `undefined_behavior` in Python are `"strict"`, `"lenient"`, and `"chainable`". Note that they are all lowercase.
