### ISSUE TITLE
Support line-based comment.

### ISSUE THREAD

**Issue by cathaysia** [mitsuhiko/minijinja#561]
![image](https://github.com/user-attachments/assets/057853b9-aee7-4f72-9132-163d29f23332)

Jinja2 support line comment, does minijinja will support it?

**Comment by mitsuhiko** [comment]
Yes, if you enable the `custom_syntax` feature you can configure line comments:

```jinja
use minijinja::{context, syntax::SyntaxConfig, Environment};

let mut env = Environment::new();
env.set_syntax(
    SyntaxConfig::builder()
        .line_statement_prefix("#")
        .line_comment_prefix("##")
        .build()
        .unwrap(),
);
```
