### ISSUE TITLE
`Value::PartialEq` not comparing iterators correctly

### ISSUE THREAD

**Issue by evroon** [mitsuhiko/minijinja#568]
Thank you for implementing jinja template rendering in Rust!

I noticed that the `PartialEq` trait for `Value` doesn't handle iterators correctly. I am specifically interested in comparing `Value`s of `HashMap`s. `PartialEq` iterates over two iterators item-by-item and compares whether two consumed items are equal. However, in the case of `HashMap` for example, the order is arbitrary. So, comparing two Values with HashMaps in it currently doesn't work.

https://github.com/mitsuhiko/minijinja/blob/42ea1a12ecc78d74d6005307542ba0482205e478/minijinja/src/value/mod.rs#L493-L495

The following piece of code I would expect to succeed, but it is flaky, it fails sometimes but also succeeds sometimes:

```rust
use std::collections::HashMap;

use minijinja::Value;

assert_eq!(
    Value::from(
        [("key1", "value1"), ("key2", "value2")]
            .iter()
            .cloned()
            .collect::<HashMap<&str, &str>>()
    ),
    Value::from(
        [("key1", "value1"), ("key2", "value2")]
            .iter()
            .cloned()
            .collect::<HashMap<&str, &str>>()
    ),
);
```

Is this intentional? If not, could we maybe, in the case of `HashMap`, use the [standard `PartialEq` implementation](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#1281-1287) of `HashMap`?

**Comment by mitsuhiko** [comment]
No, that's not intentional.  The logic for all objects should be changed to have one object iterate and then perform lookups into the other.  The same issue exists today for `Ord`.
