### ISSUE TITLE
Error message suggests improvement

### ISSUE THREAD

**Issue by sunkaifei** [mitsuhiko/minijinja#585]
At present, there are incorrect tags in the template, such as undefined tags that can cause the page to not display or indicate any errors. Is there a possibility for improvement? Also, can the prompt be improved when the template cannot be read?

**Comment by mitsuhiko** [comment]
Do you have an example of where this goes wrong?  The error is normally quite descriptive.  I feel like I need some context here.

**Comment by mitsuhiko** [comment]
Going to close this due to inactivity.
