### ISSUE TITLE
`ErrorKind::FunctionError` and `ErrorKind::FilterError`

### ISSUE THREAD

**Issue by Nukesor** [mitsuhiko/minijinja#586]
Heyo

First of all, thanks a lot for building this library! I looked for quite a while to find a library that allows custom delimiters and has good support for custom functions!

While implementing new functions, I noticed that there wasn't a good ErrorKind that matched any errors that might occur in functions/filters.
In particular, I'm currently building a dotfile/system configuration manager and I'm in the process of adding functions to integrate a variety of password managers. Those integrations include a lot of I/O.

I think it might be useful to have two very generic error kinds `FunctionError` and `FilterError` (placeholder names), to indicate to users that there was an error in a function/filter.

**Comment by mitsuhiko** [comment]
I think it would be weird for filters to produce consistent errors instead of what actually went wrong.  Is this for your own filters?  I wonder if what you need is a way to tag your own errors so you can find them later again.  Can you share a bit what you have in mind?

**Comment by Nukesor** [comment]
Yep, it's for my own filters.
The idea wouldn't be to have consistent Errors but rather a new ErrorKinds to signal that something went wrong inside of a filter/function. The specifics on what went wrong would still be contained in the details of the error.

Maybe I'm overlooking something. The [add_function](https://docs.rs/minijinja/latest/minijinja/struct.Environment.html#method.add_function) call expects a Function that returns an impl [FunctionResult](https://docs.rs/minijinja/latest/minijinja/value/trait.FunctionResult.html).  The `FunctionResult` requires `fn into_result(self) -> Result<Value, Error>;` to be implemented, where `Error` is the [minijinja::Error](https://docs.rs/minijinja/latest/minijinja/struct.Error.html).

An Minijinja Error requires an [ErrorKind](https://docs.rs/minijinja/latest/minijinja/enum.ErrorKind.html), however all ErrorKinds are specific to minijinja.

Since users can specify their own functions, they're able to perform stuff like I/O, which then may result in errors. But I'm unsure how to propagate those Errors in a proper way without using an ErrorKind that results in a confusing and unrelated error message.

**Comment by mitsuhiko** [comment]
What minijinja could do is wrap every error with a source to indicate that a filter failed.  But what is not clear to me is what you want to accomplish with this.  You cannot handle those errors anyways within templates.  Is this for error message rendering or doing something with them?

**Comment by Nukesor** [comment]
Sorry for not being clearer on this :sweat_smile:.

It's only for error message handling.
In my case, users will write configuration files that may contain templating syntax. So the errors aren't displayed for developers but rather actual users.

For example, this is such an error message:
```
Failure the first
Error: test/does_not_exist is not in the password store.
Error: Error for template at /home/nuke/repos/infrastructure/system/groups/pc/mkinitcpio.conf

Caused by:
    0: Failed to render template
    1: undefined value: Failed to execute `pass show ai/civit.com` (in file:9)
```

Right now, i'm using the `UndefinedValue` ErrorKind, because I have to specify something, but it's a bit confusing for the user.

**Comment by mitsuhiko** [comment]
Out of curiosity why are you not attaching a custom source to your error?

```rust
Error::new(ErrorKind::InvalidOperation, "Failure in filter").with_source(YourError::new("Failed to execute ..."))
```

And then when you render the error you access the source, try to downcast it into `YourError` and adjust the rendering accordingly.

I can add more `ErrorKind`s to engine for sure, but it seems to me that you probably want to play with sources instead?

**Comment by Nukesor** [comment]
Hmm, that would work.

It requires users of this library to do a bit of special error handling whenever a template error is thrown, but on the other hand, this is also a bit of a special usecase.

I still think it would be quite intuitive to have a general ErrorKind for logic that fails in functions/filters, as this solution still requires one to hijack an ErrorKind that doesn't really match the error, but I can definitely work with the `with_source` around this issue :)

Thanks for the hints and discussion, much appreciated!
