### ISSUE TITLE
Fix join() filter with `d='val'` syntax to be parity with Python Jinja2

### ISSUE THREAD

**Issue by tjsmith-meta** [mitsuhiko/minijinja#594]
## Description / Reproduction steps

The following template behaves differently with MiniJinja 2.3.1 vs Python Jinja2 2.11.3.
```
{{ ('hello', 'world') | join(d=' ') }}
```

MiniJinja output: `hello{"d": " "}world`
Python Jinja2 output: `hello world`

If MiniJinja intends not to support this syntax, I would expect that it might make sense for it to fail / return error instead of producing an output not consistent with Python Jinja2.

There's an example in the Python Jinja2 documentation that seems to suggest this syntax is part of the spec.
https://jinja.palletsprojects.com/en/2.11.x/templates/#join
```
{{ users|join(', ', attribute='username') }}
```

In the example, the `attribute` argument to `join` uses that sort of syntax, so it seems to suggest that the syntax should work for `d` as well.

**Comment by mitsuhiko** [comment]
Filters do not have _perfect_ parity.  The `attribute` part definitely makes sense supporting, the `d` part is a bit weird.  A workaround for you today is the following:

```jinja
{{ users|map(attribute='username')|join(', ') }}
```

**Comment by mitsuhiko** [comment]
This is not as bad any more.  It will now report an error for this basic usage:

```
error: invalid operation: cannot convert kwargs to string (in <string>:1)

---------------------------------- <string> -----------------------------------
   1 > {{ [1, 2, 3]|join(sep=',') }}
     i              ^^^^^^^^^^^^^ invalid operation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

While still somewhat confusing as an error message maybe, I will close this for now. I have no made up my mind yet if I want to support `attribute` on `min`/`max`/`join`.  Rest of this ticket is tracked in #596.
