### ISSUE TITLE
Keys gets reordered, unlike with the Python implementation

### ISSUE THREAD

**Issue by nospam3059** [mitsuhiko/minijinja#610]
Please consider the following input data:

```yaml
---
fruits:
  cantaloupe:
    colour: orange
  banana:
    colour: yellow
  apple:
    colour: green
```

and this template:

```jinja2
{%- for fruit in fruits -%}
{{ fruit }}: {{ fruits[fruit].colour }}
{% endfor -%}
```

Running `minijinja-cli --py-compat --no-newline fruits.txt.j2 properties.yaml` on those result in the following output:

```
apple: green
banana: yellow
cantaloupe: orange
```

The `--py-compat` flag makes no difference. The need for `--no-newline` is surprising as the closing brace is already instructed to strip whitespace, but without unintended side effects.

**Additional helpful information:**

- Version of minijinja: 2.4.0 (85c9682)
- Version of rustc: rustc 1.81.0 (eeb90cda1 2024-09-04) (built from a source tarball)
- Operating system and version: OpenBSD 7.6 GENERIC.MP#338 amd64

**Expected result**

Given the stated goal to _Stay as close as possible to Jinja2_  it is unexpected that the fruits gets reordered (i.e. sorted alphabetically?) when the Python implementation keeps their order as given in the yaml file.

Compare with the results from e.g. running either `j2 fruits.txt.j2 properties.yaml` or `jinja2-3.9 fruits.txt.j2 properties.yaml`. Where j2 comes from j2cli ([kolypto/j2cli](https://github.com/kolypto/j2cli)) in Debian, version 0.3.12b-4 and jinja2-3.9 comes from py39-jinja2-cli-0.8.2 ([mattrobenholt/jinja2-cli](https://github.com/mattrobenolt/jinja2-cli)) in FreeBSD.

```
cantaloupe: orange
banana: yellow
apple: green
```

I have not looked at minijinja's source code. Neither have I investigated nor reflected on whether yaml is giving guarantees on retaining order, but in practise it has always done so for years on multiple machines. Given that the behaviour deviating, filing a bug seems appropriate.

**Comment by mitsuhiko** [comment]
I added a PR that enables order preservation for `minijinja-cli` in the default builds.  This is a bit of an odd thing because Jinja2 never preserved order but because with Python 3.6 and later the default dictionary has order preserved, this is something that Jinja2 implicitly inherited.

**Comment by nospam3059** [comment]
That's some wizard level knowledge of Python details you've got there. Cool!

I can confirm the patched version does work and preserves order.

As a last comment for anyone stumbling upon this issue in the future it might be worth pointing out that, as suspected, yaml does not guarantee key order. There is even [section 3.2.2.1](https://yaml.org/spec/1.2.2/#3221-mapping-key-order) in the specification to make that 100% clear.
