### ISSUE TITLE
Rust .devcontainer

### ISSUE THREAD

**Issue by PopFlamingo** [mitsuhiko/minijinja#614]
Currently, if you use GitHub Codespaces or Visual Studio Code Dev Containers you need to manually define a `.devcontainer` directory to create an environment with all the necessary Rust build tools since MiniJinja doesn't define a default one. This can be a slightly cumbersome IMO especially in the case of codespaces as you must first wait for the codespace to start, manually add the files, and then rebuild the container.
Having a project defined one also has the advantage of providing a reproducible environment for all contributors as well as being useful to have with features like Copilot Workspace that I _suppose_ also leverages any existing .devcontainer to let you run commands without even needing to open a full codespace instance.

Would it make sense to add one to the repository?

**Comment by mitsuhiko** [comment]
As I'm not using codespaces I'm not familiar with that. However it does sound not particularly maintenance heavy so I would be okay with accepting a PR.

**Comment by PopFlamingo** [comment]
@mitsuhiko Yes this is a very simple configuration and very easy to update as VS Code even suggests presets, I added a new PR for it.
