### ISSUE TITLE
minjinja does not seem to support `serde_json` arbitrary-precision number types

### ISSUE THREAD

**Issue by janlugt** [mitsuhiko/minijinja#641]
I encountered an following issue while reading some JSON from disk, loading it into a `serde_json::Value`, and trying to create a minijinja context out of it:
```
let value: serde_json::Value = serde_json::from_str("{\"x\": 42}").unwrap();
println!("value = {}", value.to_string());
let string = serde_json::ser::to_string(&value).unwrap();
println!("string = {}", string);
let context = minijinja::Value::from_serialize(value);
println!("context = {}", context);
```
This gives the following output:
```
value = {"x":42}
string = {"x":42}
context = {"x": {"$serde_json::private::Number": "42"}}
```
I would expect the `minijinja::Value` to just contain `42` again. If I read the JSON as a specific rust struct, everything works, since in that case the arbitrary-precision number is not used.

Am I holding it wrong, is this expected behavior, or is it a bug?

**Comment by mitsuhiko** [comment]
This is a serde bug/limitation.  I filed an issue a long time ago in the serde repo about it: https://github.com/serde-rs/serde/issues/1463

Not much I can do here :(

**Comment by janlugt** [comment]
Thanks! If I serialize to a struct first, things work, since specific number types are known, so that's what I'll do.
