### ISSUE TITLE
Potential undefined behaviour in `KwargsValues::as_value_map`

### ISSUE THREAD

**Issue by weiznich** [mitsuhiko/minijinja#658]
## Description

I've reviewed the minijinja code as part of a regular review for our dependency updates and while doing that I noticed the following code:

https://github.com/mitsuhiko/minijinja/blob/75074708db58e3528d8589817f5843b05dd14d55/minijinja/src/value/argtypes.rs#L767-L768

As far as I can tell the `SAFETY` comment there is not sufficient because the `transmute`  turns an `Arc<KwargsValues>` into an `Arc<ValueMap>` and not only a `KwargsValues` into a `ValueMap`. The [rust standard library documentation](https://doc.rust-lang.org/std/sync/struct.Arc.html) does not specify a stable layout for `Arc<T>` (note that there is no `#[repr(…)]` on the type) so it cannot be assumed that `Arc<ValueMap>` has the same internal layout at `Arc<KwargsValues>`. 

The correct way to perform this "cast" seems to be using [`Arc::into_raw()`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.into_raw) and [`Arc::from_raw()`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.from_raw) with an intermediate pointer cast. 

Additional helpful information:

- Version of minijinja: 2.5.0
- Version of rustc: Any
- Operating system and version: Any

**Comment by mitsuhiko** [comment]
I was under the impression that since `KwargsValues` is `#[repr(transparent)]` `KwargsValues` would have the same layout as `Values` and thus `Arc<KwargsValues>` would have the same layout as `Arc<Values>`.  I will investigate this.

**Comment by weiznich** [comment]
Thanks for the fast response.

As far as I know the guarantees given by `#[repr(transparent)]` only apply to the type itself, but not to any other wrapping type. So "KwargsValues would have the same layout as Values" is true, but " Arc<KwargsValues> would have the same layout as Arc<Values>" is not true.

In practice I would assume that the layout is the same, it's just not specified (at least as long as you don't use `-Z randomize-layout` or similar functionality).

**Comment by mitsuhiko** [comment]
You're probably right. Regardless, the code makes more sense without `unsafe` anyways so I changed it.
