### ISSUE TITLE
Support `{% set %}` statements

### ISSUE THREAD

**Issue by mchesser** [mitsuhiko/minijinja#68]
Allowing set statements like jinja would help clean up some of the templates I have (e.g., conditionally building up a string which is used multiple times later in the template).

`with` statements can mostly be used as a workaround, however I've found this can get quite verbose in some cases.

**Comment by mitsuhiko** [comment]
I would be curious to see how you use it. I'm generally feeling these days that `{% set %}` creates a few annoying situations in Jinja and I try to avoid it nowadays. But maybe it really needs to still exist.

**Comment by mchesser** [comment]
Part the reason I wanted this feature probably comes from from porting some code my own preprocessing code to minijina in the most direct way as possible. I'm not overly familiar with templating languages in general, and I have mostly just been using it a simple preprocessor, so I could be missing something simple here.

First to reuse the result of a complicated expression in multiple places:

```
{% set STDOUT_PATH = "{{ROOT_DIR}}/{{TASK_NAME}}/stdout" %}
{% set TAG = "{{TASK_NAME}}_{{ID}}" %}

run_1.sh --tag {{TAG}} >> {{STDOUT_PATH}}
run_2.sh --tag {{TAG}} >> {{STDOUT_PATH}}
run_3.sh >> {{STDOUT_PATH}}
run_4.sh >> {{STDOUT_PATH}}
```

Second, building flags from optional parameters:

```
{% set FLAGS = FLAGS ~ (" -a" if ENABLE_A %}
{% set FLAGS = FLAGS ~ (" -b" if ENABLE_B %}
{% set FLAGS = FLAGS ~ ((" --mode=" ~ {{MODE}}) if MODE) %}
```

The first case is no longer much of an issue thanks to #66 and the second case is fairly straightforward to solve by just chaining all the expressions together.

Overall, I don't really have a strong need -- I just looked at the Jinja reference for a feature that would work for what I wanted and wondered why it didn't exist.

**Comment by mitsuhiko** [comment]
It shouldn't be too hard to implement. Just requires some refactoring on the scopes. I already simplified this a bit now with the introduction of unpacking in the `{% with %}` statement. Basically "just" needs that the other scopes also gain `locals`. In Jinja they are scoped to the module but the import statement can import the root scope. I don't want to implement import here though since there are also no macros in minijinja. `if` is the only statement which does not push a scope in Jinja which is already consistent with minijinja too.

**Comment by joshuataylor** [comment]
Nice!

A usecase for this is I am working on parsing files, similar to how dbt does (which uses Python/jinja). dbt uses `set` extensively to do things like assigning something to a variable -- see https://docs.getdbt.com/reference/dbt-jinja-functions/run_query (sorry, they don't have permalinks to headings).

It looks like this:

```
{% set results = run_query('select 1 as id') %}
{% do results.print_table() %}
```

It's very useful when you're giving developers jinja, you can do some very awesome stuff with just jinja & dbt without having to use Python.

**Comment by joshuataylor** [comment]
Hi!

Having set like the way it is now is great.

I know you mentioned you avoid using set in blocks, but would it be possible to support it as well? I'm unsure of the scope of it, and don't want to be a support-vampire, so I apologise. :open_hands: .

For example it's super handy to do something like this in dbt:

```sql
{% set payment_methods_query %}
select distinct id from {{ ref('stg_products') }}
order by 1
{% endset %}

{% set results = run_query(payment_methods_query) %}
```

or for lots of queries, it's super handy!

(for example with Snowflake) 
```sql
  {% set query %}
    USE ROLE SOMETHING;
    USE WAREHOUSE MY_WH;

    DELETE FROM 1;
    DELETE FROM 2;
    DELETE FROM 3;
    DELETE FROM 4;

  {% endset %}
  {% do run_query(query) %}
```
